### ISSUE TITLE
编排的使用角色列表应该是全量的角色

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1065]
**描述您遇到的bug**  
编排的使用角色列表应该是全量的角色，当前编排的使用角色列表只有登录用户的角色可选。
![image](https://user-images.githubusercontent.com/17095701/71140605-b05d8800-224c-11ea-83c1-f4f1ff396873.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@HoweChen @homiexie  有没有拿全量角色的接口？
