### ISSUE TITLE
支持对select类型数据属性的IN查询

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#1066]
## 背景和价值
**作为** 小辉，
**我想要** 在使用引用类型的数据属性作为条件进行数据对象查询时能够输入多个条件值，
**从而** 可以更灵活地确定想要查看或者操作的数据对象范围。

**Comment by chaneyliu** [comment]
建议在v2.7.0版本执行解决AC01.
AC02已在v2.4.0支持。

**Comment by royl88** [comment]
AC02已支持
