### ISSUE TITLE
服务注册不能清除目标对象类型

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1091]
**描述您遇到的bug**  
服务注册不能清除目标对象类型。
![image](https://user-images.githubusercontent.com/17095701/71225750-8c657980-2314-11ea-87ef-b73b1d206090.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
目标对象类型在可编辑状态下应提供清除功能
