### ISSUE TITLE
wecube在操作过程中会登出报权限不足错误

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1092]
**描述您遇到的bug**  
wecube在操作过程中会登出报权限不足错误。
![image](https://user-images.githubusercontent.com/17095701/71226052-773d1a80-2315-11ea-8230-f81613042367.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在插件上传的登录权限问题修复后，未再发现此类问题
