### ISSUE TITLE
CMDB插件应用新模型后插件包状态不应更新为UNREGISTERED

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1103]
**描述您遇到的bug**  
CMDB插件应用新模型后插件包状态不应更新为UNREGISTERED。
![image](https://user-images.githubusercontent.com/17095701/71237427-6bb11a00-233c-11ea-81f1-81c1d5982b7a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
这个是之前理解有误，对于拥有动态模型的插件 - 例如CMDB，当重新获取动态模型并应用了改动态模型后，该插件包还是REGISTERED状态，不用改变为UNREGISTERED。 麻烦 @BenJaMiniature Ben帮忙处理一下，前端部分逻辑 @irvinezhao 已经处理了。
