### ISSUE TITLE
任务编排的关联参数列表不应展示所有插件节点的名称

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1105]
**描述您遇到的bug**  
任务编排的关联参数列表不应展示所有插件节点的名称。
![image](https://user-images.githubusercontent.com/17095701/71238871-1bd45200-2340-11ea-8198-d1d51c880414.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@homiexie  看一下是不是开始和结束也在list里面
