### ISSUE TITLE
执行下拉菜单有空菜单

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1107]
**描述您遇到的bug**  
执行下拉菜单有空菜单
![image](https://user-images.githubusercontent.com/17095701/71239664-0f50f900-2342-11ea-86ca-bbfb236d4659.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
这个是因为海新 @haixinhuang 和经宇 @pobu168 在做批量执行，他们在用smoke数据库，插入了一条开发测试菜单数据
