### ISSUE TITLE
菜单状态列

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1116]
**描述您的需求**  
没有运行节点的插件包，在在菜单还点击，应该是灰掉，点击提示“插件包未运行，请联系管理员启动相关插件包”。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by BenJaMiniature** [comment]
菜单的状态是相对静态的，而插件的运行状态可能实时改变。如果菜单的显示需要依赖插件的运行状态，那么前端就需要不断的轮询插件的运行状态。
建议只在前端点击菜单的时候触发插件运行状态查询，即对来自于插件的菜单，前端先调用后端接口查询该插件是否有运行实例，没有则提示并灰化按钮。

**Comment by irvinezhao** [comment]
> 那么前端就需要不断的轮询插件的运行状态。

经过讨论，先在菜单表加一个状态列，status（active, inactive），
生命周期为：
插件注册后，插件菜单注入到菜单表，状态为inactive,在插件后端容器服务启动后，状态改为active，反之，销毁容器服务，状态变为inactive。
前端根据状态来判断是否灰掉菜单。
