### ISSUE TITLE
插件服务注册已decommissioned的CI属性不应可选

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1131]
**描述您遇到的bug**  
插件服务注册已decommissioned的CI属性不应可选。models接口未返回CI属性的状态。前端未根据状态过滤可选属性。
![image](https://user-images.githubusercontent.com/17095701/71346726-7c16fe00-25a3-11ea-9f68-0f517f22cc3a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@jordanzhangsz @HoweChen Jordan，豪哥，数据模型里面好像是没有CI属性的状态

**Comment by irvinezhao** [comment]
@HoweChen 请数据模型提供CI属性的状态
@homiexie  前端对应做一下状态过滤

**Comment by HoweChen** [comment]
已由 CMDB 插件修改为返回只 created 的状态。

#1309  在 unmarshal JSON 的时候也做了兼容性处理，多返回的字段不会强制匹配 DTO
