### ISSUE TITLE
上传插件失败后切换到其他页面再切回插件管理页面报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1136]
**描述您遇到的bug**  
上传插件失败后切换到其他页面再切回插件管理页面报错。
![image](https://user-images.githubusercontent.com/17095701/71348887-81c31280-25a8-11ea-8520-d8f245dc46b1.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已修复。
