### ISSUE TITLE
系统-资源管理的实例页面根据“”是否分配“”过滤查询无数据返回

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1137]
**描述您遇到的bug**  
系统-资源管理的实例页面根据“”是否分配“”过滤查询无数据返回。
Request URL: http://111.230.161.237:19090/platform/resource/items/retrieve
Request Method: POST
{"filters":[{"name":"isAllocated","operator":"eq","value":false}],"pageable":{"pageSize":10,"startIndex":0},"paging":true}

![image](https://user-images.githubusercontent.com/17095701/71351275-3a3f8500-25ae-11ea-8685-c7504fbcaecf.png)

![image](https://user-images.githubusercontent.com/17095701/71351246-26941e80-25ae-11ea-9971-130ac684efbc.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
payload is correct
![image](https://user-images.githubusercontent.com/17263271/71565586-f0ddc100-2aea-11ea-8ddb-a8f9632d977d.png)

@jordanzhangsz  please help take a look

**Comment by irvinezhao** [comment]
issue fixed
