### ISSUE TITLE
新建编排配置节点的插件时会缓存上一个节点的配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1178]
**描述您遇到的bug**  
新建编排配置节点的插件时会缓存上一个节点的配置。
![image](https://user-images.githubusercontent.com/17095701/71465289-25096700-27f7-11ea-8794-ca8bed8e547e.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
issue should fixed
