### ISSUE TITLE
查看编排节点的插件配置时confirm插件没有显示关联参数的相关配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1181]
**描述您遇到的bug**  
查看编排节点的插件配置时confirm插件没有显示关联参数的相关配置。
![image](https://user-images.githubusercontent.com/17095701/71497810-d6aaa580-2894-11ea-8828-5c1cf8152fbc.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
the issue can not be reproduced, already fixed
