### ISSUE TITLE
查看已执行的流程图，没有展示目标对象和任务的绑定关系

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1190]
**描述您遇到的bug**  
查看已执行的流程图，没有展示目标对象和任务的绑定关系。
![image](https://user-images.githubusercontent.com/17095701/71506996-f4d8cb80-28bd-11ea-86b8-685f35f513a4.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
duplicate with #1284
