### ISSUE TITLE
批量执行 - bugs

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1210]
![image](https://user-images.githubusercontent.com/17263271/71573876-0077fc80-2b21-11ea-98be-70623b47d5ae.png)

**Comment by pobu168** [comment]
第一个问题前端来处理，第二个问题前端只能根据返回的状态显示，其实关机了也是执行失败了，需要产品看下这里要怎么优化！

**Comment by pobu168** [comment]
问题一 fixed

**Comment by haixinhuang** [comment]
第二问题是插件包版本不对，更换插件包即可
