### ISSUE TITLE
系统参数 - bugs

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1211]
**描述您遇到的bug**  
1， 后台问题： 注册后状态还是inactive
![image](https://user-images.githubusercontent.com/17263271/71575332-85feab00-2b27-11ea-9e5f-453c6c4fcf7d.png)
2， 前端问题：下拉范围里没有具体的插件，导致没有回显
![image](https://user-images.githubusercontent.com/17263271/71575348-9151d680-2b27-11ea-89e0-cda87e5e68b4.png)

3, 前端和后端 都只能过滤Global和plugin-package,要能过滤具体的插件包名
![image](https://user-images.githubusercontent.com/17263271/71576607-19d27600-2b2c-11ea-9f85-aee897a3196e.png)

4， 根据”来源“过滤无效

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by haixinhuang** [comment]
问题已定位到原因，具体如下：
主要原因是system_variables表结构变更导致这些问题。
1， 后台问题： 注册后状态还是inactive
原因：未制定xml编写规范，导致插件包中的xml仍未修改。
解决方案：修改插件开发规范文档和包含系统参数内容的xml（目前排查只有artifacts、monitor、saltstack）
2， 前端问题：下拉范围里没有具体的插件，导致没有回显
原因：因系统参数表结构变更，该值取值范围发生变化。
解决方案：此属性需要前端限制不允许用户修改，后端不更新该属性。
3, 前端和后端 都只能过滤Global和plugin-package,要能过滤具体的插件包名
原因：因系统参数表结构变更，该值取值范围发生变化。
解决方案：需要后端新增接口返回下拉列表的数据，前端配合修改。
4， 根据”来源“过滤无效
经验证，不存在这个问题
