### ISSUE TITLE
批量执行结果不展示多选引用的内容

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1227]
**描述您遇到的bug**  
批量执行结果不展示多选引用的内容。
![image](https://user-images.githubusercontent.com/17095701/71649937-b2940c00-2d4d-11ea-98ce-e2da94080a87.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
2020.01.02 @kanetz Tong:
"- #1227 #1228，目前的实现中确实影响了到某些查询结果表格中某些数据属性的显示，但是由于WeCube模型中通用id和name属性列的方案还未确定，作为遗留issue在GitHub里追踪，在之后的迭代中进行修复"

**Comment by chaneyliu** [comment]
建议在v2.8.0版本优化批量执行数据展示。
