### ISSUE TITLE
批量执行结果展示引用数据的guid而不是keyname，展示枚举的code而不是value

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1228]
**描述您遇到的bug**  
批量执行结果展示引用数据的guid而不是keyname，展示枚举的code而不是value。
![image](https://user-images.githubusercontent.com/17095701/71650068-96449f00-2d4e-11ea-82e8-1a06101cc26b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
2020.01.02 @kanetz Tong:
"- #1227 #1228，目前的实现中确实影响了到某些查询结果表格中某些数据属性的显示，但是由于WeCube模型中通用id和name属性列的方案还未确定，作为遗留issue在GitHub里追踪，在之后的迭代中进行修复"

**Comment by chaneyliu** [comment]
建议与#1227合并在v2.8.0优化解决。
