### ISSUE TITLE
批量执行查询配置有缓存

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1229]
**描述您遇到的bug**  
批量执行配置查询进行查询后，点击“清空条件”，再点击“定义查询”，路径起点的下拉选项缓存了之前的选项，没有返回全量的下拉菜单。
![image](https://user-images.githubusercontent.com/17095701/71650160-38fd1d80-2d4f-11ea-8dde-859bb648264f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
Done
