### ISSUE TITLE
批量执行查询出结果后页面不支持再次查询

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1230]
**描述您遇到的bug**  
批量执行查询出结果后页面不支持再次查询。
![image](https://user-images.githubusercontent.com/17095701/71650573-c477ae00-2d51-11ea-82d8-548d0898541d.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
点击 蓝色的那条就可以搜索了
