### ISSUE TITLE
服务注册 - 同一个服务多次注册后，出现异常

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#1277]
**描述您遇到的bug**  
服务注册 - 同一个服务多次注册:
1.先注册一个 “注册名称”为空的服务
2.复制第一个服务，然后注册；
3.复制第二个服务，然后注册。

然后发现，已注册第一个和第二个服务显示的interface为空。

**Comment by irvinezhao** [comment]
![image](https://user-images.githubusercontent.com/17263271/71961326-0f059880-3232-11ea-9962-79789f7ecbff.png)

**Comment by pobu168** [comment]
Done
