### ISSUE TITLE
流程编排执行优化

### ISSUE THREAD

**Issue by pobu168** [WeBankPartners/wecube-platform#1284]
**描述您的需求**  

- [ ] 1、流程执行历史在所有节点均成功时取消定时刷新功能

- [ ] 2、流程节点内容展示在显示名过长出现重叠现象

      （根据图像长度与字体数量计算显示字体大小）

- [x] 3、下拉框应都是可以清除的

- [ ] 4、查询历史执行时，目标对象执行的历史数据没有回显（ #1190 查看已执行的流程图，没有展示目标对象和任务的绑定关系。 ） 
![image](https://user-images.githubusercontent.com/17263271/71945750-989d7200-3202-11ea-97b9-3f895bbf5c7e.png)

**作为**<角色>
**我想要**<>
**从而**<>

**附加**

**Comment by irvinezhao** [comment]
第3个问题已经修复

**Comment by pobu168** [comment]
第4个问题已经修复
