### ISSUE TITLE
流程编辑bug

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1292]
**描述您遇到的bug**  
1， 删除没有二次确认
![image](https://user-images.githubusercontent.com/17263271/71972126-079cba00-3247-11ea-90a8-269f5332489b.png)
2，样式覆盖
3，选择编排编辑权限时没有回显
![image](https://user-images.githubusercontent.com/17263271/71972220-361a9500-3247-11ea-9684-c295a7d820c2.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
#1285 在这个issue中修复
