### ISSUE TITLE
编排执行 绑定关系不对

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1325]
**描述您遇到的bug**  
如图，节点2是没有目标可以选择，但是右侧图上却出现了 ‘2’

**如何重现** 

**预期行为** 

**截图**  

**附加**
![image](https://user-images.githubusercontent.com/17263271/72318604-ad34ab00-36d7-11ea-9eaa-1f244c8ed164.png)

**Comment by pobu168** [comment]
Done
