### ISSUE TITLE
编排执行 - 保留了悬浮内容全屏的状态

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1326]
**描述您遇到的bug**  
在编排执行页面，悬浮左侧的流程节点，然后点击全屏，这时关闭弹出框，再次悬浮，出现的弹出框直接是最大化的，预期是悬浮打开时都是小的弹出框

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
V5，这都测的到！
