### ISSUE TITLE
WeCube登录问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1349]
**描述您遇到的bug**  
1. 首次打开wecube url页面提示权限状态错误
![image](https://user-images.githubusercontent.com/17095701/72487395-d0329c80-3848-11ea-8c94-b5a297997bd6.png)
2. 登录后语言栏不显示语言信息
![image](https://user-images.githubusercontent.com/17095701/72487528-46370380-3849-11ea-89e4-604aa4bc4b56.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
已经改为401不提示，直接跳转到登录页面
