### ISSUE TITLE
插件注册运行管理页面展开对象存储时报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1350]
**描述您遇到的bug**  
插件注册运行管理页面展开对象存储时报错
![image](https://user-images.githubusercontent.com/17095701/72487904-63200680-384a-11ea-9b16-3aa02306c9be.png)

Request URL: http://111.230.161.237:19090/platform/v1/packages/wecmdb__v2.25.2/resources/s3/files
Request Method: GET

Response：{"status":"ERROR","message":"d != java.lang.String","data":null}

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@junchensz 帮忙看看

**Comment by chaneyliu** [comment]
建议在v2.7.0版本排期展示对象存储内容。

**Comment by chaneyliu** [comment]
v2.6.0已修复
