### ISSUE TITLE
导入编排页面未显示编排内容

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1353]
**描述您遇到的bug**  
在打开一个编排的时候导入编排，页面未显示编排内容。
![image](https://user-images.githubusercontent.com/17095701/72499820-e30b9800-386d-11ea-9ddb-5af932df1708.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@homiexie HM帮忙看看
