### ISSUE TITLE
启动插件的端口不能自主选择

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#1361]
**描述您的需求**  
启动插件端口从20000开始，不可以自主选择。
**作为**用户
**我想要**启动插件端口可以自主选择
**从而**<>

**附加**

**Comment by haixinhuang** [comment]
@DeliaDing123 你的需求没写完呢~
从而 <> ??

我们之前有考虑过让用户输入端口，并分析过两种方案（用户输入、系统自动分配）的优缺点。

方案一的优点是可以让用户自主选择输入哪个端口，让用户更自由；
但缺点也很明显，要求用户需要知道选择的容器母机上有哪些可用端口，用户需要登录到母机上检查或者母机多的时候用户容易记错，否则创建过程很容易因为端口被占用而失败；

方案二的优点是节省用户操作（点一下比输入一个端口也算节省了），不需要用户事先知道母机有哪些可用端口，减少人为错误；
缺点就是用户不能自主选择端口输入。

在系统运行过程中，运行一个容器只需要一个可用端口即可，无论是用户自主选择的端口，还是程序按照某些逻辑来分配的端口，只要不被占用就是可用的。

身为研发，考虑的可能不够周全，如果你作为用户有其他的想法，可以一起讨论
