### ISSUE TITLE
在wecube启动CMDB插件报错信息不明确

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1374]
**描述您遇到的bug**  
在wecube启动CMDB插件报错信息不明确.
1. 在资源管理配置了docker主机未配置mysql主机
![image](https://user-images.githubusercontent.com/17095701/73633144-e342ca80-4698-11ea-958e-ae34ddeb5ae7.png)
2. 启动cmdb插件报错信息为index:0, 错误应提示缺少mysql主机资源配置.
![image](https://user-images.githubusercontent.com/17095701/73633182-fce41200-4698-11ea-9f87-0423eaa01968.png)
![image](https://user-images.githubusercontent.com/17095701/73633193-040b2000-4699-11ea-86c8-cc16f58eed0f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@HoweChen  豪哥瞅瞅

**Comment by chaneyliu** [comment]
建议在v2.6.0版本加强插件注册启动的报错信息优化。

**Comment by chaneyliu** [comment]
已修复。
