### ISSUE TITLE
在wecube运行wecmdb插件时如果前一次创建db成功但是未启动成功会导致下一次启动失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1375]
**描述您遇到的bug**  
在wecube运行wecmdb插件时如果前一次创建db成功但是未启动成功会导致下一次启动失败.
![image](https://user-images.githubusercontent.com/17095701/73634977-69f9a680-469d-11ea-868b-7b4525be19be.png)
![image](https://user-images.githubusercontent.com/17095701/73636250-66b3ea00-46a0-11ea-9a25-be32e4dc4063.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
建议在v3.0.0版本重构时，增加插件注册、启动的事务性保证能力。

**Comment by gavin2lee** [comment]
Implemented in Wecube 3.2.2.
