### ISSUE TITLE
在wecube运行wecmdb插件执行scp错误导致启动失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1376]
**描述您遇到的bug**  
在wecube运行wecmdb插件执行scp错误导致启动失败.
![image](https://user-images.githubusercontent.com/17095701/73637207-b2679300-46a2-11ea-87a1-418bfb82720c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by haixinhuang** [comment]
经排查，原因是因为mysql资源服务器和docker资源服务器用了同一个IP，而代码逻辑只根据IP查找docker资源服务器，导致使用mysql资源服务器的端口去做scp。
需要修改代码来修复。
