### ISSUE TITLE
给用户添加角色不方便

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1392]
**描述您的需求**  

**作为**<管理员>
**我想要**<给用户（例如用户dev1）添加角色，目前只能通过去不同的角色添加该用户dev1，而不能从用户的角度去修改角色信息，导致操作繁琐>
**从而**<简单易用的修改用户的角色>

**附加**

**Comment by chaneyliu** [comment]
建议在v2.8.0排期优化。
