### ISSUE TITLE
插件注册的xml中，定义在authories里的内容没有注入到Wecube中

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#1407]
**描述您的需求**  
插件注册的xml中，定义在authories里的内容没有注入到Wecube中。

**作为**<用户>
**我想要**<在插件注册时xml中，声明在authories中的角色拥有哪些菜单的权限，将会在注册插件包后生效>

**从而**<允许插件预先定义 授权菜单给角色>

**附加**

**Comment by HoweChen** [comment]
目前需要插件注册后在 web 页面：

系统 - 权限管理 中手动配置 角色与插件之间的权限绑定关系。

会修改为插件注册后自动绑定
