### ISSUE TITLE
插件包注册后 没有菜单

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1415]
**描述您遇到的bug**  

插件包注册后 没有菜单

**如何重现** 

**预期行为** 
预期有菜单回显，但是状态为inactive，直到插件容器启动后，菜单可用

**截图**  

**附加**

**Comment by HoweChen** [comment]
现在是插件注册后手动在页面完成绑定。会在 #1407 ，修复。
