### ISSUE TITLE
wecube菜单的管理功能

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1494]
**描述您的需求**  

**作为**<角色>
**我想要**<在UI界面上可以对菜单进行配置管理>
**从而**<可以做到灵活配置我的菜单>

**附加**

![image](https://user-images.githubusercontent.com/17263271/75013081-6dbf6280-54be-11ea-9998-21ffea9efb65.png)

**AC1 ：新增父级菜单**
 点击新增父级菜单，打开弹窗，显示需要新建父级菜单需要填充的字段：
 菜单的唯一键（code）input required
 本地语言显示名称(local_display_name) input required
 英语语言显示名称(en_display_name) input required
 描述(description) input
其中，新增父级菜单的id自动生成(用code字段填写)，父级菜单的parent为null，source为SYSTEM，菜单顺序为父菜单最后一个。

**AC2：修改父菜单**
点击父菜单的修改，打开弹窗，显示可以修改的父级菜单字段：
菜单的唯一键（code）input required
 本地语言显示名称(local_display_name) input required
 英语语言显示名称(en_display_name) input required
 描述(description) input 

**AC3： 调整父菜单顺序**
通过点击父菜单上的上箭头或下箭头，来调整父菜单的顺序，第一个父菜单不可继续上移，最后一个父菜单不可下移。

**AC4： 删除父菜单**
点击父菜单的删除，需要做二次确认才能删除

**AC5：增加子菜单**
点击父菜单右侧的新增可以给该父菜单新增一个子菜单，需要填写字段：
 菜单的唯一键（code）input required
 本地语言显示名称(local_display_name) input required
 英语语言显示名称(en_display_name) input required
 描述(description) input
 是否为外部跳转(is_redirect) select required
 外部跳转链接(redirect_url) input required(if is_redirect)
其中，新增子菜单的id自动生成(用父菜单code+code字段填写)，父级菜单的parent为当前选中父菜单，source为SYSTEM，菜单顺序为该父菜单里的最后一个子菜单。

**AC6: 修改子菜单**
点击子菜单的修改，打开弹窗，显示可以修改的子菜单字段：
菜单的唯一键（code）input required
 本地语言显示名称(local_display_name) input required
 英语语言显示名称(en_display_name) input required
 描述(description) input
 是否为外部跳转(is_redirect) select required
 外部跳转链接(redirect_url) input required(if is_redirect)

**AC7： 调整子菜单顺序**
通过点击子菜单上的上箭头或下箭头，来调整子菜单的顺序，第一个子菜单不可继续上移，最后一个子菜单不可下移。

**AC8： 删除子菜单**
点击子菜单的删除，需要做二次确认才能删除

**Comment by chaneyliu** [comment]
建议在v3.0.0重构版本增加此功能。
