### ISSUE TITLE
数据同步功能

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1533]
**描述您的需求**  
1、生产、容灾、准生产环境，使用一套WeCube，由生产运维角色使用。DEV、SIT、STG环境，使用一套WeCube，由测试、开发角色使用。两套环境可以同步数据。
2、应用架构设计（第一层）、资源规划设计（第六层）的数据，只能在生产wecube环节维护，并同步到测试wecube。
3、物料管理数据，只能在测试wecube维护，并同步到生产wecube。
4、编排数据，编排大部分在测试wecube维护，并同步到生产wecube。

**Comment by chaneyliu** [comment]
建议在v2.7.0版本排期实现。
