### ISSUE TITLE
建议编排任务执行页面的“执行预览”按钮在未配置编排的时候不显示

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#155]
**描述您的需求**  
建议编排任务执行页面的“执行预览”按钮在未配置编排的时候不显示。
现在点击未配置编排数据的“执行预览”按钮报错不友好。

![image](https://user-images.githubusercontent.com/17095701/64004322-9f272900-cb40-11e9-97ad-58a1ca35fb9c.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
2.0 design will fix this automatically
