### ISSUE TITLE
配置任务编排的插件列表未列出符合条件的插件列表

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1552]
**描述您遇到的bug**  
配置任务编排的插件列表未列出符合条件的插件列表, 如huaweicloud/vpc 已经注册,但是列表没有提供可选.
如cmdb的插件列表返回多个版本的列表,不知道该选哪个.
![image](https://user-images.githubusercontent.com/17095701/77272757-e8151980-6cec-11ea-8fcc-d34df4157ef6.png)
![image](https://user-images.githubusercontent.com/17095701/77272844-227eb680-6ced-11ea-97b0-7594a4bdc960.png)
![image](https://user-images.githubusercontent.com/17095701/77272970-712c5080-6ced-11ea-9c5c-970ebe8dd728.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by haixinhuang** [comment]
已经fixed，请重新部署master分支验证
