### ISSUE TITLE
建议在配置插件服务接口时高亮当前正在配置的接口

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1556]
**描述您遇到的bug**  
建议在配置插件服务接口时高亮当前正在配置的接口， 要不然不知道当前正在配置哪个。
插件注册〉服务注册〉huaweicloud_v1.1〉服务注册〉 security-group点击添加
![image](https://user-images.githubusercontent.com/17095701/77275603-a9369200-6cf3-11ea-9145-081aa7194c14.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在 #1587 中修复
