### ISSUE TITLE
对插件服务进行权限控制

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#1561]
**描述您的需求**  
1. 增加插件权限管理功能
在插件注册页面，添加插件服务权限管理功能。

2. 进行插件服务权限控制
2.1 在编排设计页面，选中某可折叠子流程节点， 点击插件下拉列表获取数据时，（假设当前编排属主角色R1-list 和 当前用户的角色R2-list，R1-list和R2-list的交集 是R3-list），拉取出来的必须是R3-list拥有权限的插件；
2.2 编排保存时，需要校验编排的属主角色是否拥有其调用的所有插件服务权限，若否则不允许保存。
2.3 批量执行选择插件服务时，需要根据当前用户的所有角色过滤可用的插件服务。

**作为**<角色>
**我想要**<>
**从而**<>

**附加**

**Comment by haixinhuang** [comment]
由于角色信息保存在auth-server的数据库中，所以在platform-core中，建立role_name与plugin_config_interfaces.service_name建立绑定关系。

**Comment by haixinhuang** [comment]
在插件包上传解析时，若已存在该插件包的旧版本，那么新版本的插件服务需要继承旧版本的已授权信息，所以需要修改插件包上传功能。

**Comment by chaneyliu** [comment]
#1858合并跟踪处理。
