### ISSUE TITLE
配置任务编排节点的插件项时下拉列表显示重复的插件接口

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1576]
**描述您遇到的bug**  
配置任务编排节点的插件项时下拉列表显示重复的插件接口。
![image](https://user-images.githubusercontent.com/17095701/77404803-39a4cd80-6ded-11ea-8f41-a572e5e14960.png)
![image](https://user-images.githubusercontent.com/17095701/77404873-4e816100-6ded-11ea-9d21-dab53ea6585c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
dup issue
