### ISSUE TITLE
执行编排节点未根据选择绑定的数据执行

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1578]
**描述您遇到的bug**  
执行编排节点未绑定数据时节点执行错误。该节点仍然下发数据执行插件接口。

![image](https://user-images.githubusercontent.com/17095701/77408786-31e82780-6df3-11ea-9cad-a59f07a2f532.png)
![image](https://user-images.githubusercontent.com/17095701/77408831-46c4bb00-6df3-11ea-8cdf-c0ff3487d246.png)

执行步骤5只绑定一条数据执行时， 该节点步骤仍执行所有数据。
![image](https://user-images.githubusercontent.com/17095701/77410591-103c6f80-6df6-11ea-83d3-ababf72e04ea.png)
![image](https://user-images.githubusercontent.com/17095701/77410647-2a764d80-6df6-11ea-85f1-068934dcf4fc.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed.

**Comment by yolanda0209** [comment]
这个编排执行数据反选的问题又出现了。
