### ISSUE TITLE
执行编排时获取不到被关联CI的属性数据

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1580]
**描述您遇到的bug**  
执行编排时获取不到被关联CI的属性数据。 如图执行编排的“创建NAT”节点时获取不到子网的id。
编排执行结果：
![image](https://user-images.githubusercontent.com/17095701/77418739-47b11900-6e02-11ea-9d55-a04b3677c833.png)
插件任务接口配置：
![image](https://user-images.githubusercontent.com/17095701/77418779-58618f00-6e02-11ea-8285-346d647dfa57.png)
任务编排配置：
![image](https://user-images.githubusercontent.com/17095701/77418823-6c0cf580-6e02-11ea-8cf8-762dc96ebb5f.png)

综合查询返回的子网ID信息：
![image](https://user-images.githubusercontent.com/17095701/77419106-d756c780-6e02-11ea-974d-77328326a61c.png)

wecube log：
[wecubelog.txt](https://github.com/WeBankPartners/wecube-platform/files/4374853/wecubelog.txt)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
#1614
