### ISSUE TITLE
执行编排目标对象列表无数据返回时不应在页面弹框报Error

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1584]
**描述您遇到的bug**  
执行编排目标对象列表无数据返回时不应在页面弹框报Error。
![image](https://user-images.githubusercontent.com/17095701/77553182-70fba300-6eef-11ea-9101-54d275b50371.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在 #1587中修复
