### ISSUE TITLE
任务编排配置节点的插件服务下拉菜单未列出符合条件的列表

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1585]
**描述您遇到的bug**  
任务编排配置节点的插件服务下拉菜单未列出符合条件的列表。
如huaweicloud的vpc服务接口已注册，但是任务编排配置节点的插件服务下拉菜单未列出该服务接口。列表还列出其他重复的接口。
![image](https://user-images.githubusercontent.com/17095701/77598546-11c47f80-6f3d-11ea-80af-2d6c09f8e4e4.png)
![image](https://user-images.githubusercontent.com/17095701/77598561-1d17ab00-6f3d-11ea-8fb3-a6baf7d1085a.png)
![image](https://user-images.githubusercontent.com/17095701/77598575-243eb900-6f3d-11ea-8800-68633f308336.png)
![image](https://user-images.githubusercontent.com/17095701/77598584-302a7b00-6f3d-11ea-91b4-6742a3ab0ff3.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by haixinhuang** [comment]
已修复，请验证 @yolanda0209
