### ISSUE TITLE
保存编排节点配置有时console报错Cannot read property 'procDefName' of undefined导致保存不生效

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1586]
**描述您遇到的bug**  
保存编排节点配置有时console报错Cannot read property 'procDefName' of undefined导致保存不生效。
![image](https://user-images.githubusercontent.com/17095701/77598641-53edc100-6f3d-11ea-8768-00a064469253.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在#1587 中修复
