### ISSUE TITLE
执行编排节点失败后再次点击失败节点时不应弹出数据选择框

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1596]
**描述您遇到的bug**  
执行编排节点失败后再次执行时数据没有过滤，不勾选数据执行仍然执行了第一次的数据。
[qcloud_log.txt](https://github.com/WeBankPartners/wecube-platform/files/4387927/qcloud_log.txt)
[wecube_log02.txt](https://github.com/WeBankPartners/wecube-platform/files/4387929/wecube_log02.txt)

1. 插件接口配置过滤规则为vpc_asset_id eq ''
![image](https://user-images.githubusercontent.com/17095701/77637056-fafb4880-6f8f-11ea-9ac9-a8995f257d56.png)
2. 执行插件编排创建vpc，点击编排的vpc节点，有6条记录可选，选择4条记录点击执行，实际成功3条并更新了ci的vpc_asset_id，一条失败。
![image](https://user-images.githubusercontent.com/17095701/77639257-6eeb2000-6f93-11ea-82de-c28e28ac24d0.png)

![image](https://user-images.githubusercontent.com/17095701/77658791-268f2a80-6fb2-11ea-8c10-4c93bd8a9a42.png)
网段ci的vpc_asset_id更新了创建成功的三个vpc id
![image](https://user-images.githubusercontent.com/17095701/77658973-6c4bf300-6fb2-11ea-929b-036c44d5c3e1.png)

3. 再次点击编排的vpc节点，这时仍然弹出6条记录默认勾选了之前执行的4条数据，在这里如果根据过滤条件vpc_asset_id eq '' 应该只弹出3条没创建的记录。
![image](https://user-images.githubusercontent.com/17095701/77659184-b03ef800-6fb2-11ea-99ec-0e0f1316a775.png)
![image](https://user-images.githubusercontent.com/17095701/77660745-acac7080-6fb4-11ea-9c5b-209d2e3f4280.png)

4. 这时一条数据都不勾选点击重试，预计无数据执行，实际执行了第一次的4条数据。
![image](https://user-images.githubusercontent.com/17095701/77659550-293e4f80-6fb3-11ea-9b37-d25f68a53af7.png)
![image](https://user-images.githubusercontent.com/17095701/77659779-6e628180-6fb3-11ea-9e57-fbf44c57cc92.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
前端不应弹出两个窗口

**Comment by pobu168** [comment]
Fixed
