### ISSUE TITLE
执行编排节点插件接口调用返回成功但是最终结果失败且未解析出错误信息 ------error message 需要截取

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1597]
**描述您遇到的bug**  
执行编排节点插件接口调用返回成功但是最终结果失败且未解析出错误信息。
![image](https://user-images.githubusercontent.com/17095701/77678942-dec9cc80-6fcc-11ea-82b5-448c9668c8da.png)
![image](https://user-images.githubusercontent.com/17095701/77679212-35370b00-6fcd-11ea-82b6-6ad91f6ab6ec.png)
![image](https://user-images.githubusercontent.com/17095701/77679345-5e579b80-6fcd-11ea-8d04-5ce55bcc4ce8.png)

Qcloud日志：
![image](https://user-images.githubusercontent.com/17095701/77679689-dd4cd400-6fcd-11ea-9742-d87bb84b137b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
error message 需要截取
