### ISSUE TITLE
插件服务注册接口配置参数属性的页面展示问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1598]
**描述您遇到的bug**  
配置插件服务注册接口的属性的页面展示问题：
1. 显示插件接口参数的框太小了，一般接口的输入参数比较多，不方便查看和配置
2. 参数属性的列表有时向上展开被截断不方便查看和配置
![image](https://user-images.githubusercontent.com/17095701/77681814-e25f5280-6fd0-11ea-9093-1e5de0260907.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
未复现

**Comment by homiexie** [comment]
后期这一块会替换新控件，暂时不予修复
