### ISSUE TITLE
配置服务注册接口的参数属性时根属性后面不应允许继续输入

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1604]
**描述您遇到的bug**  
配置服务注册接口的属性时根属性后面不应允许继续输入，如下图
![image](https://user-images.githubusercontent.com/17095701/77820866-77249600-7120-11ea-8b50-70cddea66f74.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
后期替换新的交互控件，因为不影响使用，暂时不予修复
