### ISSUE TITLE
插件服务注册添加新的服务注册直接点击注册时，左边菜单导航没有刷新

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1609]
**描述您遇到的bug**  
插件服务注册添加新的服务注册，输入注册名称后直接点击注册时，左边菜单导航没有刷新导致已保存的服务在页面上不可见，这时点击保存按钮提示该服务已存在。
![image](https://user-images.githubusercontent.com/17095701/77843834-739e1700-71d3-11ea-9512-be1942455534.png)
![image](https://user-images.githubusercontent.com/17095701/77843862-c7a8fb80-71d3-11ea-91c9-47b11f5cdb66.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在 #1587 中修复
