### ISSUE TITLE
日志文件没有分包，转存，备份处理。

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#162]
**描述您的需求**  
wecube, cmdb , 插件的日志文件没有分包，压缩，转存，备份处理。cmdb的日志如果有Info级别大小增长很快，因为用户的每个操作都会记录到info日志里。但是日志没有进行处理会比较占空间。

**预期行为**  
建议进行分包，压缩，转存，备份处理。

**描述您考虑过的替代方案**  
每礼拜打包一次转存到类似nfs的地方。

**附加**
![image](https://user-images.githubusercontent.com/46696471/64016902-c5f25900-cb5a-11e9-83ca-45f5d36a7c7d.png)

**Comment by gavin2lee** [comment]
@irvinezhao 现在we3日志已经分文件，默认保留最近30天日志。这个issue应该可以关闭了。
@DeliaDing123
