### ISSUE TITLE
编排执行未根据运行状态+已注册状态执行插件服务接口

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1623]
**描述您遇到的bug**  
编排执行未根据运行状态+已注册状态执行插件服务接口.
如wecmdb_v1.4.2.3插件版本已运行并已注册, 新版本wecmdb_v1.4.2.4已注册未运行. 编排执行cmdb的插件接口报错"errorMessage":"No instance for plugin [wecmdb] is available."}
![image](https://user-images.githubusercontent.com/17095701/78123395-b0227a80-7440-11ea-9ad3-706b90c6c70d.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已在#1881 解决。
