### ISSUE TITLE
插件服务注册的属性配置系统参数，列表有多个CMDB URL

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1624]
**描述您遇到的bug**  
插件服务注册的属性配置系统参数，列表有多个CMDB_URL. 历史版本的参数仍然是active状态。
![image](https://user-images.githubusercontent.com/17095701/78150928-8c742a00-746a-11ea-9116-a3c3fcb35474.png)
![image](https://user-images.githubusercontent.com/17095701/78151198-ea087680-746a-11ea-996e-cc3ba7f0be3e.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
这个接口要根据当前相应插件的版本过滤一下吧 @irvinezhao
