### ISSUE TITLE
插件执行的多选引用入参获取数据的顺序问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1633]
**描述您遇到的bug**  
华为云lb target接口多个主机和多个端口有一一对应的关系，现在插件执行lb target的删除接口删除后端服务器时获取到多选引用入参主机id的顺序和端口对应不上导致在云上匹配不到资源，接口返回成功实际上云上未删除相应的资源。
![image](https://user-images.githubusercontent.com/17095701/78504208-13dcd880-779e-11ea-88e9-397b282ac9be.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by gavin2lee** [comment]
因为cmdb返回的多选引用前后顺序不一致。如下面报文
INFO  c.w.w.p.c.s.d.StandardEntityOperationRestClient  - SEND QUERY post [1586101866647] url=http://10.0.2.10:19110/wecmdb/entities/lb_instance/query, request={"criteria":{"attrName":"id","condition":"0053_0000000002"},"additionalFilters":[]}
INFO  c.w.w.p.c.s.d.StandardEntityOperationRestClient  - RECEIVE QUERY post [1586101866647] url=http://10.0.2.10:19110/wecmdb/entities/lb_instance/query,result=[status=OK, message=Success, data=[{lb_listener_asset_id=, code=test1, r_guid=0053_0000000002, displayName=STGi_TEST_TEST_PC1001_test1, description=, target_hosts=[0031_0000000019, 0031_0000000020], protocal=tcp, host_ports=8082,8183, lb_resource_instance=0035_0000000003, key_name=STGi_TEST_TEST_PC1001_test1, p_guid=null, unit=0048_0000000005, port=8081, guid=0053_0000000002, id=0053_0000000002, state=created, fixed_date=, state_code=created}]]
===========================================================================================================
===========================================================================================================
INFO  c.w.w.p.c.s.d.StandardEntityOperationRestClient  - SEND QUERY post [1586101868278] url=http://10.0.2.10:19110/wecmdb/entities/lb_instance/query, request={"criteria":{"attrName":"id","condition":"0053_0000000002"},"additionalFilters":[]}
INFO  c.w.w.p.c.s.d.StandardEntityOperationRestClient  - RECEIVE QUERY post [1586101868278] url=http://10.0.2.10:19110/wecmdb/entities/lb_instance/query,result=[status=OK, message=Success, data=[{lb_listener_asset_id=, code=test1, r_guid=0053_0000000002, displayName=STGi
_TEST_TEST_PC1001_test1, description=, target_hosts=[0031_0000000020, 0031_0000000019], protocal=tcp, host_ports=8082,8183, lb_resource_instance=0035_0000000003, key_name=STGi_TEST_TEST_PC1001_test1, p_guid=null, unit=0048_0000000005, port=8081, guid=0053_0000000002, id=
0053_0000000002, state=created, fixed_date=, state_code=created}]]

**Comment by chaneyliu** [comment]
建议在3.0版本重构时解决数据关联问题。
