### ISSUE TITLE
执行编排调用错误的插件版本执行接口

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1644]
**描述您遇到的bug**  
华为云插件启动了两个版本，huaweicloud_v1.1.4.2 和 huaweicloud_v1.1.4.3 都启动了，现在执行编排的日志记录在huaweicloud_v1.1.4.2, huaweicloud_v1.1.4.2版本都没有注册该服务。
插件日志：
![image](https://user-images.githubusercontent.com/17095701/78737677-ac33b280-7982-11ea-84f0-e980466a042d.png)
![image](https://user-images.githubusercontent.com/17095701/78737681-b190fd00-7982-11ea-9df5-e1702ce4dcad.png)

wecube日志：
![image](https://user-images.githubusercontent.com/17095701/78737698-beadec00-7982-11ea-9895-cc1cba185a75.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by gavin2lee** [comment]
#1712 included this bug
