### ISSUE TITLE
插件配置属性不会根据目标对象赋默认值, 属性没有值不能注册

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1650]
**描述您遇到的bug**  
插件配置属性不会根据目标对象赋默认值, 属性没有值不能注册。
![image](https://user-images.githubusercontent.com/17095701/78796297-b7b9c480-79e8-11ea-83e3-5dfe86b97230.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
在 #1640 分支上修复了
