### ISSUE TITLE
编辑CI数据保存从前端传入的旧数据会覆盖数据库已更新的新数据

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1661]
**描述您遇到的bug**  
编辑CI数据保存从前端传入的旧数据会覆盖数据库已更新的新数据。
![image](https://user-images.githubusercontent.com/17095701/78970436-dd0b1780-7b3b-11ea-9ca3-76eee91f73d0.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
建议cmdb在8月份版本，通过数据库记录最后更新时间字段与提交报错的系统时间对比，如提交后台时间晚于数据库记录时间，提示客户保存失败，原因“有更新数据存在，请刷新后重新编辑保存”。
