### ISSUE TITLE
获取所有插件包的信息接口返回太慢

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#1662]
**描述您遇到的bug**  
点开插件注册菜单，获取所有插件包的信息接口返回太慢

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
建议在v2.6.0版本发布中解决。

**Comment by royl88** [comment]
已优化插件包接口效率
