### ISSUE TITLE
插件服务注册在接口点击添加，然后点击删除会把这个服务接口都删掉

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1669]
**描述您遇到的bug**  
插件服务注册在接口点击添加，然后点击删除会把这个服务接口都删掉。
Request URL: http://111.230.161.237:19090/platform/v1/plugins/configs/huaweicloud__v1.1.4.6__public-ip
Request Method: DELETE
![image](https://user-images.githubusercontent.com/17095701/79196621-fd501480-7e62-11ea-9744-aa0daf63ba2b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
已在v2.5.0版本修复。
