### ISSUE TITLE
编排执行图形展示的字超出图框字体叠加

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1672]
**描述您遇到的bug**  
编排执行图形展示的字超出图框字体叠加。
![image](https://user-images.githubusercontent.com/17095701/79302439-f5ee4100-7f1e-11ea-8917-d0618ffe8556.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
issue fixed
