### ISSUE TITLE
在执行编排查看的消息没有渲染转义字符

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1674]
**描述您遇到的bug**  
在执行编排查看的消息没有渲染“\r\n”，反斜杠等转义字符.
![image](https://user-images.githubusercontent.com/17095701/79319938-93f00480-7f3b-11ea-9d13-b94d29fd5d96.png)
![image](https://user-images.githubusercontent.com/17095701/79408926-255c8680-7fcf-11ea-9281-c93ea2836bc4.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@pobu168 经宇帮忙看看这个小问题
