### ISSUE TITLE
任务编排执行和查询输入框建议提供删除功能

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1676]
**描述您遇到的bug**  
任务编排执行和查询输入框建议提供删除功能。
![image](https://user-images.githubusercontent.com/17095701/79409461-9fd9d600-7fd0-11ea-8b6a-ef91c9cdd47c.png)
![image](https://user-images.githubusercontent.com/17095701/79409530-c992fd00-7fd0-11ea-916b-fc0871a8c962.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
编排执行历史不应该能删除。

**Comment by chaneyliu** [comment]
建议在v2.6.0版本优化解决。

**Comment by pobu168** [comment]
Done
