### ISSUE TITLE
新增系统参数不填写描述信息保存报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1677]
**描述您遇到的bug**  
新增系统参数不填写描述信息保存报错。描述信息不应该是必填项，报错信息也不明确。
![image](https://user-images.githubusercontent.com/17095701/79537799-96766980-80b5-11ea-994a-eb3fa877a583.png)
删除系统参数报错的信息提示用的是描述字段。

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
描述不应该是必填项，麻烦两位兄弟看看怎么解决一下 @homiexie @haixinhuang

**Comment by haixinhuang** [comment]
> 描述不应该是必填项，麻烦两位兄弟看看怎么解决一下 @homiexie @haixinhuang

可排期解决。

**Comment by chaneyliu** [comment]
建议在v2.7.0版本排期解决。

**Comment by gavin2lee** [comment]
fixed

**Comment by royl88** [comment]
资源管理，描述不填写无法提交问题，未解决，排期v2.8.0修复
