### ISSUE TITLE
插件注册运行容器下拉菜单没有实时获取主机列表

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1678]
**描述您遇到的bug**  
在系统参数页面增删docker主机，插件注册运行容器下拉菜单没有实时获取主机列表。
![image](https://user-images.githubusercontent.com/17095701/79538749-86f82000-80b7-11ea-85b2-24190e622603.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
拉取可用主机接口挂到Select打开时请求 @homiexie
