### ISSUE TITLE
删除代码中一些已经废弃的类，还需要删除代码中存储下来的临时文件，以免浪费磁盘空间

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#1690]
**描述您的需求**  
1.删除代码中一些已经废弃的类
2.删除代码中存储下来的临时文件，以免浪费磁盘空间
插件启动接口中，会从S3上下载插件包存到本地/tmp/{timestamp}/目录下，需要代码逻辑中删除该目录

**作为**<角色>
**我想要**<>
**从而**<>

**附加**

**Comment by gavin2lee** [comment]
fixed
