### ISSUE TITLE
配置插件服务注册目标对象的过滤条件不要影响已有的属性配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1699]
**描述您的需求** 
配置插件服务注册目标对象的过滤条件不要影响已有的属性配置。 
插件服务注册目标对象的过滤条件不需要拷贝到属性配置。
![image](https://user-images.githubusercontent.com/17095701/80166794-59f4c180-8611-11ea-9664-2a4fcc9d4b87.png)

**附加**

**Comment by chaneyliu** [comment]
建议在3.0版本排期优化。
