### ISSUE TITLE
修改编排任务实体类型的过滤规则不要影响插件节点的定位规则

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1702]
**描述您的需求**  
修改编排任务实体类型的过滤规则不要影响插件节点的定位规则
![image](https://user-images.githubusercontent.com/17095701/80182594-d8fdf000-8639-11ea-8d65-ee4ee898fe39.png)

**附加**

**Comment by chaneyliu** [comment]
建议在3.0版本排期优化。

**Comment by pobu168** [comment]
编排任务实体类型的过滤规则不带入插件节点

**Comment by pobu168** [comment]
#1699
