### ISSUE TITLE
建议任务编排节点的插件列表根据定位规则的CI来匹配，不应包含过滤规则匹配

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1703]
**描述您的需求**  
建议任务编排节点的插件列表根据定位规则的CI来匹配，不应包含过滤规则匹配。
![image](https://user-images.githubusercontent.com/17095701/80184995-3136f100-863e-11ea-8739-e32c127b2a18.png)

**附加**

**Comment by chaneyliu** [comment]
需要包含过滤规则，否则很容易选错插件服务。
