### ISSUE TITLE
填写数据转到其他表格再回来，编辑数据消失

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#1705]
**描述您遇到的bug**  
在机房规划设计填写业务区域设计编辑过程中去查看网段设计的资料，回来业务区域设计数据都没有了，

**如何重现** 

**预期行为** 
已经编辑的数据应该还是存在于页面的，不应该显示成了消失

**截图**  
![image](https://user-images.githubusercontent.com/46696471/80196448-048bd500-8650-11ea-89d9-fbf55dba5cc6.png)

**附加**

**Comment by irvinezhao** [comment]
issue will fixed in new table component
