### ISSUE TITLE
wecube用户数据丢失

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1707]
**描述您遇到的bug**  
wecube用户数据丢失。
![image](https://user-images.githubusercontent.com/17095701/80197893-e6bf6f80-8651-11ea-9356-c2943909c2ef.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
建议在9月份的版本排期解决。

**Comment by gavin2lee** [comment]
目前应该已经没有这样的问题出现。
