### ISSUE TITLE
插件注册目标对象类型的修改的响应很慢

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1709]
**描述您的需求**  
插件注册目标对象类型的修改响应很慢，删除或配置需要十几秒才完成
![image](https://user-images.githubusercontent.com/17095701/80299966-48571980-87cb-11ea-98eb-6ee75ebb375f.png)

**附加**

**Comment by chaneyliu** [comment]
已在v2.6.1版本解决。
