### ISSUE TITLE
按文档提示无法安装

### ISSUE THREAD

**Issue by youmu0007** [WeBankPartners/wecube-platform#1766]
**描述您遇到的bug**  
[root@localhost wecube-platform]# make build
mkdir -p repository
docker run --rm --name wecube-build  -e SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass -v /data/wecub                                  e_repository:/usr/src/mymaven/repository -v /data/wecube-platform/build/maven_settings.xml:/usr/share/maven/ref/                                  settings-docker.xml  -v /data/wecube-platform:/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn -U clean                                   install -Dmaven.test.skip=true -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
[INFO] Scanning for projects...
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/springframework/boot/spring-boot-starter-pa                                  rent/2.1.3.RELEASE/spring-boot-starter-parent-2.1.3.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.webank.wecube.platform:wecube-platform:1.0-SNAPSHOT: Could not transfe                                  r artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.3.RELEASE from/to alimaven (http://maven.                                  aliyun.com/nexus/content/groups/public/): maven.aliyun.com: Temporary failure in name resolution and 'parent.rel                                  ativePath' points at no local POM @ line 6, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.webank.wecube.platform:wecube-platform:1.0-SNAPSHOT (/usr/src/mymaven/pom.xml) has 1 e                                  rror
[ERROR]     Non-resolvable parent POM for com.webank.wecube.platform:wecube-platform:1.0-SNAPSHOT: Could not tra                                  nsfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.3.RELEASE from/to alimaven (http://ma                                  ven.aliyun.com/nexus/content/groups/public/): maven.aliyun.com: Temporary failure in name resolution and 'parent                                  .relativePath' points at no local POM @ line 6, column 13: Unknown host maven.aliyun.com: Temporary failure in n                                  ame resolution -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@haixinhuang 麻烦帮忙跟进一下

**Comment by royl88** [comment]
文档已更新，可以参考最新v2.5.0安装体验文档：[安装体验说明](https://wecube-1259801214.cos.ap-guangzhou.myqcloud.com/v2.5.0/WeCube%E5%85%A8%E9%87%8F%E4%BD%93%E9%AA%8C%E8%BF%87%E7%A8%8B%E8%AF%B4%E6%98%8Ev2.5.0.pdf)
