### ISSUE TITLE
物料包管理页面删除物料包后，页面不应显示已删除物料包的差异化变量配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#1782]
**描述您遇到的bug**  
物料包管理页面删除物料包后页面不应显示已删除物料包的差异化变量配置
![image](https://user-images.githubusercontent.com/17095701/82857095-8ff3d100-9f42-11ea-9209-dd287a2d05f7.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by pobu168** [comment]
DONE
