### ISSUE TITLE
POM包括特殊的repo

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1790]
不同用户可能出现的maven找不到包的问题，建议把特殊的repo写入项目的pom，而不是在maven的setting里面。

**Comment by gavin2lee** [comment]
做到开源代码“即得即用”，尽量减少开源代码pull后的额外配置：
1）将标准cental repo外的依赖移动到相应工程的pom文件；从而不需要额外配置meven的settings.xml;
2)去掉lombok依赖。
