### ISSUE TITLE
应用部署的数据库脚本可否支持多个

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#1864]
在应用部署时，现在只能选择一个初始化脚本（界面为单选），是否可以支持多个脚本按顺序执行的情况呢？ 比如一个脚本是DDL，一个是初始化数据；或者初始化数据再两个初始化sql文件里，需要全部执行

**Comment by royl88** [comment]
已于saltstack & artifacts plugin中完成，closing...
