### ISSUE TITLE
应用实例升级无法编辑

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#1871]
**描述您遇到的bug**  
应用升级的时候，新物料包已上传，单元已经更改部署包版本，应用实例无法编辑；
规避办法：在应用实例右侧按钮点击“启动”，然后点击“确认"，完后应用实例可以编辑选择新的部署包，跑升级编排升级应用。

**如何重现** 
应用实例更新部署包时可重现。
wecube 2.4.0
wecmdb 1.5.0

**预期行为** 

**截图**  

**附加**

**Comment by chaneyliu** [comment]
原因：
CMDB的数据状态机确少两条状态迁移路径。

**Comment by chaneyliu** [comment]
解决方案：
在CMDB数据库内执行如下SQL
INSERT INTO `wecmdb_embedded`.`adm_state_transition` (`id_adm_state_transition`, `current_state`, `current_state_is_confirmed`, `target_state`, `target_state_is_confirmed`, `operation`, `action`, `status`) VALUES ('60', '42', '1', '42', '0', '46', '53', 'active');
INSERT INTO `wecmdb_embedded`.`adm_state_transition` (`id_adm_state_transition`, `current_state`, `current_state_is_confirmed`, `target_state`, `target_state_is_confirmed`, `operation`, `action`, `status`) VALUES ('61', '42', '0', '42', '1', '47', '55', 'active');
