### ISSUE TITLE
希望可以在portal页面上可以访问离线本地的帮助文档

### ISSUE THREAD

**Issue by royl88** [WeBankPartners/wecube-platform#1889]
**描述您的需求**  
希望可以在portal页面上可以访问离线本地的帮助文档，而非访问外部github文档
**作为**系统管理员
**我想要**在内网部署wecube时可以访问帮助文档/更快的帮助文档访问
**从而**提高使用wecube时获取帮助的效率

**附加**内网部署时无法访问github帮助文档/因github访问慢，需要提供portal本地的帮助文档访问方式，快速使用

**Comment by kanetz** [comment]
UAT passed
