### ISSUE TITLE
按照开发环境配置[WeCube开发环境配置]无法启动（文档版本过于陈旧）

### ISSUE THREAD

**Issue by shenhonglei** [WeBankPartners/wecube-platform#1911]
**描述您遇到的bug**  
[WeCube Developer Guide](https://github.com/WeBankPartners/wecube-platform/blob/master/wecube-wiki/docs/developer/wecube_developer_guide.md) 文档能否更新最新版本匹配，包括截图部分。以便于大家更容易的按照开发手册，来更快速的入门， 非常感谢。

**如何重现** 

**预期行为** 

及时更新开发者手册，非常感谢
**截图**  

**附加**

**Comment by royl88** [comment]
感谢反馈，将安排8月份进行文档更新
如果是希望快速安装&体验wecube，还可以参照这个文档 [全量体验说明](https://wecube-1259801214.cos.ap-guangzhou.myqcloud.com/v2.5.0/WeCube%E5%85%A8%E9%87%8F%E4%BD%93%E9%AA%8C%E8%BF%87%E7%A8%8B%E8%AF%B4%E6%98%8Ev2.5.0.pdf)

**Comment by shenhonglei** [comment]
期待…
