### ISSUE TITLE
【CMDB CI删除】删除上有CI数据时，未校验是否存在下游的CI数据

### ISSUE THREAD

**Issue by TylerTang06** [WeBankPartners/wecube-platform#1938]
**描述您遇到的bug**  
比如，已存在调用设计A和调用A1；此时， 删除调用设计A，删除成功；查看对应的系统时，系统会报错，此时系统数据关系乱套。

**预期行为** 
所以，用户删除调用设计A时，系统应该校验已存在调用A1，提示不能删除调用设计A（需要先删除调用A1，才能删除调用设计A）。

**Comment by chaneyliu** [comment]
在没有定版前，不应该有录入调用数据。不是bug
