### ISSUE TITLE
【CI数据修改】上游CI数据修改“唯一名称”后，需要分别手动更新下手CI数据

### ISSUE THREAD

**Issue by TylerTang06** [WeBankPartners/wecube-platform#1940]
**描述您遇到的bug**  

比如，存在系统设计A，系统A_1，子系统设计SA_1，当修改系统设计A"唯一名称"为B；需要手动更新（手动触发编辑按钮+保存按钮）系统A_1为B_1，子系统SA_1为SB_1;而手动更新了子系统设计，对应的子系统和单元设计等数据也需要依次去手动更新；依次类推。

**Comment by chaneyliu** [comment]
系统功能设计就是这样的，不是bug。
