### ISSUE TITLE
差异化变量中支持全局静态值配置

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#1954]
**描述您的需求**  

**作为一个**懒惰**的WeCube使用人员，
**我想要一个在差异化变量中支持全局静态值的配置功能，
**从而我在配置应用差异化变量时，对于全局统一的变量值，如WeCube公钥，只需要引用相同的变量表达式，而不用给每个子系统再配置相同的配置值。

**附加**
![image](https://user-images.githubusercontent.com/52971115/90887118-5d912d00-e3e6-11ea-9664-836ad6a09c82.png)

**Comment by chaneyliu** [comment]
这种配置应该通过表达式选取到对应的CI。比如在部署环境这个CI上增加一个属性记录wecube公钥。
