### ISSUE TITLE
插件注册报错

### ISSUE THREAD

**Issue by zhanghongxia4725** [WeBankPartners/wecube-platform#1960]
报错信息如下：The Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 162EAAF6149EA404)
s3服务器是自己搭建的minio，能访问

![微信图片编辑_20200826085028](https://user-images.githubusercontent.com/67135700/91242260-89f7d100-e779-11ea-8e8d-a6a777dc7b35.jpg)

**Comment by royl88** [comment]
您提供的报错信息不够，可以提供详细的场景及配置内容描述以便定位
建议检查一下 access_key（secret_key）这几个位置的输入正确：
1. platform-core容器启动docker-compose.yml => 环境变量S3_ACCESS_KEY={your_access_key}
2. web页面-系统-系统参数：system__global__S3_ACCESS_KEY=={your_access_key}
3. web页面-系统-资源管理：s3资源填写的用户名/密码

**Comment by royl88** [comment]
若无进一步讨论，即将关闭ISSUE...
