### ISSUE TITLE
在本地搭建好环境后，下载了官方的插件（代码和插件都是V2.6发行版），进行插件注册，能成功，任务编排和编排执行均报错

### ISSUE THREAD

**Issue by zhanghongxia4725** [WeBankPartners/wecube-platform#1969]
能不能给一个完整的用户手册指导我们进行相关功能的使用，现有的部署手册，开发者手册均不是最新的，而且描述极其含糊，谢谢各位开源作者

**Comment by royl88** [comment]
这份文档就是最新的，按照步骤进行操作：[体验说明](https://wecube-1259801214.cos.ap-guangzhou.myqcloud.com/v2.5.0/WeCube%E5%85%A8%E9%87%8F%E4%BD%93%E9%AA%8C%E8%BF%87%E7%A8%8B%E8%AF%B4%E6%98%8Ev2.5.0.pdf)
1. 自动化安装部署(默认部署到腾讯云)
2. 自动化注册插件
3. demo应用的部署编排流程上线/下线

**Comment by royl88** [comment]
若无进一步讨论，即将关闭ISSUE...
