### ISSUE TITLE
WeCube用户连续操作时也经常会过期登出

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/wecube-platform#1972]
**描述您遇到的bug**  
WeCube用户连续操作时经常会过期退出，操作时间间隔不超过5分钟

**预期行为** 
WeCube用户连续操作时，如时间停顿不超过30分钟（WeCube默认时间），不应该频繁退出

**Comment by royl88** [comment]
更改为：1. 不依赖于前端expire时间校验， 2. 当access token失效后，应发出refresh请求，若刷新token成功，则重试用户请求，若刷新token失败，则置空token，跳转登陆

**Comment by royl88** [comment]
已解决。
