### ISSUE TITLE
ci数据复制新增页面，删除按钮逻辑错误

### ISSUE THREAD

**Issue by xuxuzhesi** [WeBankPartners/wecube-platform#1995]
**描述您遇到的bug**  
ci数据复制新增页面，删除按钮逻辑错误

**如何重现** 
勾选多条ci数据，点击复制新增，在弹出的修改框中删除其中一条

**预期行为** 
页面删掉了对应要删除的数据
实际行为：
删除了排序在要删除数据前的所有数据
**截图**  

**附加**

**Comment by pobu168** [comment]
Done
