### ISSUE TITLE
首页 / 系统 / 权限管理  点击菜单，有的时候所有权限都没有了

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#2012]
**描述您遇到的bug**  
首页 / 系统 / 权限管理  点击菜单，有的时候所有权限都没有了

**如何重现** 

首页 / 系统 / 权限管理  点击菜单，勾选权限， 然后回到用户发现所有权限都没有了
**预期行为** 

勾选的权限有， 没有勾选的权限没有。 正常显示。 
**截图**  

**附加**

**Comment by chaneyliu** [comment]
请在9月底2.6.2版本修复解决。

**Comment by royl88** [comment]
已解决。
