### ISSUE TITLE
修改旧密码的时候输入的旧密码当时设置的密码，  而是加密后的字符串。 

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#2025]
**描述您遇到的bug**  
修改旧密码的时候输入的旧密码当时设置的密码，  而是加密后的字符串。 

**如何重现** 
进入app_instance 修改密码。 输入的旧密码是 加密之后的字符串。 

**预期行为** 

**截图**  
![image](https://user-images.githubusercontent.com/46696471/93978925-42cc2280-fdaf-11ea-8f0a-84f620842e63.png)

**附加**

**Comment by DeliaDing123** [comment]
这个修改密码的方式是不是可以导致任何人随意修改密码？

**Comment by royl88** [comment]
CMDB权限设计是通过控制数据可见性来管理的，详见系统管理-CMDB数据权限管理。
方式：没有权限的数据即不可见，或者可见但只读，比如授权系统A给用户A管理，授权系统B给用户A只读，那么用户A仅能看到系统A/B数据，且用户A是系统A的管理者仅能修改系统A的数据，并不会存在任意人可修改的问题，合理使用数据权限功能即可。

**Comment by chaneyliu** [comment]
密码修改分为cmdb记录和实际密码。cmdb记录修改通过权限控制。salt的密码修改插件也有权限控制。
单独修改cmdb的记录，并不会对实际密码产生影响，需要有权限的角色在通过编排调用salt的修改密码插件，修改完成的密码会加密回写cmdb。cmdb并不知道密码的加密算法和加密算法，只是记录文本串。
