### ISSUE TITLE
优化插件实例列表的页面展示

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#2053]
**描述您的需求**  

**作为**<用户>，目前页面上的展示不够清晰，两个插件实例的销毁按钮容易误点。
**我想要**<页面展示不同实例间的分界更加清晰>
**从而**<避免用户误操作，展示更美观>

**附加**
![image](https://user-images.githubusercontent.com/22583258/96951122-6b664a00-151e-11eb-99ae-ed2bc9cd2c78.png)

**Comment by homiexie** [comment]
已在 #2048 中优化
