### ISSUE TITLE
目前插件实现了注册，但是网关路由不知怎么处理

### ISSUE THREAD

**Issue by zhanghongxia4725** [WeBankPartners/wecube-platform#2054]
**描述您遇到的bug**  
插件注册成功，调用/gateway/v1/route-items接口可以看到这些注册后的路由信息，但是注册成功后的菜单不能动态跳转，目前实现的是手动将注册成功后的插件IP，端口修改到nginx.conf这个配置文件中，这样不方便，能实现网关自动转发这些注册后的插件路由吗

**如何重现** 

**预期行为** 

希望早点回复
**截图**  

**附加**

**Comment by royl88** [comment]
是自己编写的新插件吗，还是使用wecube官方的插件？一般是不需要改动nginx配置的，插件包上传后，确认注册，CORE会处理路由信息不用手动修改。

**Comment by zhanghongxia4725** [comment]
自己写的插件，不是官方的，我看CORE里面是会注册路由，然后GATEWAY里面也对动态路由进行了处理，问题是这个GATEWAY里面的路由相关接口前端portal中都没有调用，怎么个机制啊

**Comment by royl88** [comment]
确实目前每一个新插件都需要修改nginx配置，增加一项
location /{plugin-name} {
    proxy_pass http://core;
}
原因是/默认指向portal页面，如果不定义是会导致404。
这是一个问题，需要安排修复。

**Comment by royl88** [comment]
v2.8.0版本已修复。
