### ISSUE TITLE
插件服务增加描述字段，在选择使用该插件服务时可查看描述

### ISSUE THREAD

**Issue by homiexie** [WeBankPartners/wecube-platform#2072]
**描述您的需求**  

**作为**<角色>
用户
**我想要**<>
插件服务增加描述字段
**从而**<>
在选择使用该插件服务时可查看描述
**附加**
![image](https://user-images.githubusercontent.com/40050306/98063107-3cd76000-1e8a-11eb-96a4-d75715246e38.png)

**Comment by chaneyliu** [comment]
请在9月底版本实现

**Comment by pobu168** [comment]
已修复，鼠标悬停将显示描述字段
