### ISSUE TITLE
platform高危插件支持

### ISSUE THREAD

**Issue by gavin2lee** [WeBankPartners/wecube-platform#2090]
Core批量执行接口更改：
1. 前端调用 - 若存在高危插件的运行实例 - (No)直接调用批量执行 
                |
                |- (Yes)调用检测接口 - 返回的response.data.data列表长度大于等于1 - (No) 直接调用批量执行 
                                        |
                                        | - (Yes)返回Confirm信息 - 前端弹出 - 用户确认 - 重新进入前端调用，并附带query参数/v1/xxxx?continue_token=xxx - 校验token - (No)返回status: ERROR
                                                                    |                                                                                      |
                                                                    | - 用户取消                                                                           | - (Yes)直接调用批量执行

Core的Confirm返回示例：
{
    status: CONFIRM, 
    data: {continue_token: xxxx}
    message: "+-------+------------------------------------+----------------+--------------------------------------------------------+\n| Line  |              Content               |    Message     |                     Source Script                      |\n+=======+====================================+================+========================================================+\n|  1-1  | DROP TABLE `box`;                  | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.0/v1.0.0.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n|  8-8  | update table_name set name='test'; | \u66f4\u65b0\u5168\u91cf\u6570\u636e\u8868 | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n| 14-14 | DROP TABLE IF EXISTS `box`;        | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n|  1-1  | DROP TABLE `box`;                  | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.2/v1.0.2.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+"
}

高危命令插件 检测接口
Request:
POST /itsdangerous/v1/batch_execution_detection
{
    // 可选
    "operator": admin,
    // 必选
    "serviceName": "qcloud/vm(resource)/create",
    // 可选
    "servicePath": "/qcloud/v1/vm/create",
    // 可选，建议传，提升检测速度
    "entityType": "wecmdb:host_resource_instance"
    // 必选
    "entityInstances": [{"id": "xxx_xxxxxx"}],
    // 必选，serviceName对应的调用参数列表
    "inputParams": [
        {"xml define prop": xxx},
        {...},
        {..}
    ]
}

Response
{
    "code":200,
    "status":"OK",
    "data":{
        "text":"+-------+------------------------------------+----------------+--------------------------------------------------------+\n| Line  |              Content               |    Message     |                     Source Script                      |\n+=======+====================================+================+========================================================+\n|  1-1  | DROP TABLE `box`;                  | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.0/v1.0.0.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n|  8-8  | update table_name set name='test'; | \u66f4\u65b0\u5168\u91cf\u6570\u636e\u8868 | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n| 14-14 | DROP TABLE IF EXISTS `box`;        | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+\n|  1-1  | DROP TABLE `box`;                  | \u5220\u9664\u6570\u636e\u8868     | demo-app-spring-                                       |\n|       |                                    |                | boot_1.5.3/sql/rollback/v1.0.2/v1.0.2.sql              |\n+-------+------------------------------------+----------------+--------------------------------------------------------+",
        "data":[
            {
                "lineno":[
                    1,
                    1
                ],
                "level":"critical",
                "content":"DROP TABLE `box`;",
                "message":"\u5220\u9664\u6570\u636e\u8868",
                "script_name":"demo-app-spring-boot_1.5.3/sql/rollback/v1.0.0/v1.0.0.sql"
            },
            {
                "lineno":[
                    8,
                    8
                ],
                "level":"high",
                "content":"update table_name set name='test';",
                "message":"\u66f4\u65b0\u5168\u91cf\u6570\u636e\u8868",
                "script_name":"demo-app-spring-boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql"
            },
            {
                "lineno":[
                    14,
                    14
                ],
                "level":"critical",
                "content":"DROP TABLE IF EXISTS `box`;",
                "message":"\u5220\u9664\u6570\u636e\u8868",
                "script_name":"demo-app-spring-boot_1.5.3/sql/rollback/v1.0.1/v1.0.1.sql"
            },
            {
                "lineno":[
                    1,
                    1
                ],
                "level":"critical",
                "content":"DROP TABLE `box`;",
                "message":"\u5220\u9664\u6570\u636e\u8868",
                "script_name":"demo-app-spring-boot_1.5.3/sql/rollback/v1.0.2/v1.0.2.sql"
            }
        ]
    },
    "message":"success"
}

**Comment by pobu168** [comment]
[批量执行接口说明.txt](https://github.com/WeBankPartners/wecube-platform/files/5571758/default.txt)
