### ISSUE TITLE
使用 wecube 部署的应用，jvm 里面的编码是 ANSI，而自己手动使用 start 脚本启动时，编码是 UTF-8

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#2102]
**描述您遇到的bug**  
机器上echo $LANG  是 UTF-8 ；在 wecube 界面上传应用包，然后，使用界面上的编排执行进行部署，然后 ssh 登录服务器查看编码，显示 ANSI，再命令执行 stop/start 后，编码变成 UTF-8。

**如何重现** 

**预期行为** 
和echo  $LANG应该要是一样值

**截图**  
![image](https://user-images.githubusercontent.com/46696471/100581709-17236680-3323-11eb-8457-92c397b22100.png)

![image](https://user-images.githubusercontent.com/46696471/100581714-1a1e5700-3323-11eb-890b-c197d4a22806.png)

**附加**

**Comment by zgyzgyhero** [comment]
1、saltstack远程执行时没有指明编码，所以用的是系统基础的ANSI
2、建议java应用应该指定自身运行时的编码，因为saltstack不太好直接固定死编码，如果有不同的应用需要不同的编码时就会有问题，所以最好还是应用自己决定
3、在local运行时用utf-8是因为目标主机本地环境变量有配置用utf-8
