### ISSUE TITLE
支持使用公钥身份验证建立SSH连接

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#2142]
1. Method
    com.webank.wecube.platform.core.service.CommandService#runAtRemote(String, String, String, Integer, String)
    - Found usages  (4 usages found)
        - platform-core  (4 usages found)
            - com.webank.wecube.platform.core.service.plugin  (4 usages found)
                - PluginInstanceService  (1 usage found)
                    - createPluginDockerInstance(PluginPackage, String, CreateInstanceDto)  (1 usage found)
                        - 892 commandService.runAtRemote(hostIp, hostInfo.getLoginUsername(), loginPassword,
                - PluginPackageService  (3 usages found)
                    - deployPluginUiResourcesIfRequired(PluginPackage)  (2 usages found)
                        - 1133 commandService.runAtRemote(remoteIp, pluginProperties.getStaticResourceServerUser(),
                        - 1157 commandService.runAtRemote(remoteIp, pluginProperties.getStaticResourceServerUser(),
                    - removePluginUiResourcesIfRequired(PluginPackage)  (1 usage found)
                        - 1185 commandService.runAtRemote(staticResourceIp, pluginProperties.getStaticResourceServerUser(),

1. Method
    com.webank.wecube.platform.core.service.ScpService#put(String, Integer, String, String, String, String)
    - Found usages  (2 usages found)
        - platform-core  (2 usages found)
            - com.webank.wecube.platform.core.service.plugin  (2 usages found)
                - PluginInstanceService  (1 usage found)
                    - createPluginDockerInstance(PluginPackage, String, CreateInstanceDto)  (1 usage found)
                        - 873 scpService.put(hostIp, Integer.valueOf(hostInfo.getPort()), hostInfo.getLoginUsername(), password,
                - PluginPackageService  (1 usage found)
                    - deployPluginUiResourcesIfRequired(PluginPackage)  (1 usage found)
                        - 1145 scpService.put(remoteIp, pluginProperties.getStaticResourceServerPort(),

**Comment by gavin2lee** [comment]
Fixed
