### ISSUE TITLE
WeCube平台服务端口不可配置

### ISSUE THREAD

**Issue by Austinchen-4374** [WeBankPartners/wecube-platform#2201]
ISSUE：
当前WeCube平台服务写死端口19090/19120/19110/19100/19101，切换成其他端口会导致服务不可用, 
在通过K8s安装时会出现两个问题：
        a. 安装wecube时必须修改客户提供的K8s（ps.K8s默认不支持19xxx端口）
        b. 假设某19xxx端口被占用，则wecube无法安装成功
   验收标准：
        a. 切换成K8s默认支持的端口（30000~32767），服务能正常使用

**Comment by chaneyliu** [comment]
可以通过修改配置文件来更改启动端口
