### ISSUE TITLE
资源远程管理控制台/WebShell

### ISSUE THREAD

**Issue by nevinxie** [WeBankPartners/wecube-platform#334]
## 背景和价值
**作为** 小锋（应用运维专家）和 小辉（基础运维专家），
**我希望** 能够在WeCube上针对主机、数据库实例等资源启动远程管理控制台（WebShell），
**从而** 在不需要以人工方式直接连接登录资源的情况下完成日常运维管理工作，
由此避免人工操作可能引起的技术和业务风险，
并且满足对运维操作的审计管理要求。

### AC01. 重命名“执行 - 编排任务执行”菜单项
**假定** 小锋或小辉成功登录访问WeCube，
**当** 他打开 **“执行”** 菜单时，
**那么** 他应当可以在菜单项"应用部署"和"批量执行"之间找到 **“任务执行”** 菜单项，
并且其功能替换了原来的 **“编排任务执行”** 菜单项。

![image](https://user-images.githubusercontent.com/1160645/65413641-75ea7780-de24-11e9-9092-5f31e5cd901f.png)

### AC02. 主机/虚拟机实例管理
**假定** 小辉通关菜单项“执行 - 任务执行”进入了任务执行页面，
**当** 他打开CMDB中的 **主机** 对应的页面标签时，
**那么** 他可以在查询列表中固定在最后的 **“Actions”** 列中找到 **“控制台...”** 按钮，
**当** 他点击 **“控制台...”** 按钮时，
**那么** WeCube应当在弹出的新窗口中开启一个自动连接并免密登录到对应虚拟机实例的SSH控制台页面，
并且弹出窗口的标题（Title）中应当包含高区分度的关键性信息（如“_IP地址_的SSH控制台”），
并且他可以在控制台页面中完成常用的WebShell操作（可参考常见WebShell组件功能）。

![image](https://user-images.githubusercontent.com/1160645/65414200-cc0bea80-de25-11e9-876e-9470a59cfde5.png)

### AC03. Mysql实例管理
**假定** 小锋通关菜单项“执行 - 任务执行”进入了任务执行页面，
**当** 他打开CMDB中的 **数据库** 对应的页面标签时，
**那么** 他可以在查询列表中固定在最后的 **“Actions”** 列中找到 **“控制台...”** 按钮，
**当** 他点击 **“控制台...”** 按钮时，
**那么** WeCube应当在弹出的新窗口中开启一个自动连接并免密登录到对应数据库实例的控制台页面，
并且弹出窗口的标题（Title）中应当包含高区分度的关键性信息（如“_IP地址_的mysql控制台”），
并且他可以在控制台页面中完成常用的Mysql客户端操作（可参考mysql）。

### AC04. Redis实例管理
**假定** 小锋通关菜单项“执行 - 任务执行”进入了任务执行页面，
**当** 他打开CMDB中的 **Redis** 对应的页面标签时，
**那么** 他可以在查询列表中固定在最后的 **“Actions”** 列中找到 **“控制台...”** 按钮，
**当** 他点击 **“控制台...”** 按钮时，
**那么** WeCube应当在弹出的新窗口中开启一个自动连接并免密登录到对应Redis实例的控制台页面，
并且弹出窗口的标题（Title）中应当包含高区分度的关键性信息（如“_IP地址_的redis控制台”），
并且他可以在控制台页面中完成常用的Redis客户端操作（可参考redis-cli）。

### AC05. WeCube记录控制台访问的审计日志
**假定** 小辉或小锋通关菜单项“执行 - 任务执行”进入了任务执行页面，
**当** 他打开与CMDB中的某个资源相关的远程管理控制台页面时，
**那么** **WeCube**应当记录此次访问控制台操作的审计日志，
并且日志中应当包括此次操作相关的时间、用户、CI类型、CI对象实例、插件、连接及登录结果。

### AC06. 插件记录控制台操作命令的审计日志
**假定** 小辉或小锋通关菜单项“执行 - 任务执行”进入了任务执行页面，
并且打开了与CMDB中的某个资源相关的远程管理控制台页面，
**当** 他在控制台中执行操作命令时，
**那么** 提供此控制台功能的**插件**应当记录此次控制台连接会话中执行的所有命令的审计日志，
并且日志中应当包括每条命令的执行时间、插件、用户、连接参数、输入命令及输出结果。

## 假设与限制
1. 主机的WebShell目前仅需支持安装了Linux操作系统的虚拟机实例。

## 备注
1. 资源管理控制台功能应当覆盖绝大部分可行的资源类型，基于目前WeCube上支持的资源，目前仅考虑了虚拟机实例、mysql实例、redis实例；作为日常运维工作中执行维度的便捷功能，WeCube可以提供通用机制以供其它的资源管理插件进行开发支持。
1. 远程管理控制台的功能实现通常要与CMDB中某个特定的CI类型绑定，因此WeCube核心平台可能需要记录和维护某个CI类型和为这个类型提供远程管理控制台功能的特定插件之间的关系。
1. 可考虑使用WebSocket以增强用户使用WebShell的交互体验。

**Comment by kanetz** [comment]
创建新的issue #915 以供追踪，所以关闭此issue
