### ISSUE TITLE
建议插件注册的参数区分必选和可选参数

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#339]
**描述您的需求**  
建议插件注册的参数区分必选和可选参数。当前系统未区分必选参数和可选参数，一定要所有参数都配置了才可以保存。

![image](https://user-images.githubusercontent.com/17095701/65412295-851bf600-de21-11e9-8ac4-2b281b875061.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
2.0设计就没有这块了，全部都是只读。
