### ISSUE TITLE
任务编排的导出和导入

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#347]
## 背景和价值
**作为** 小辉（基础运维专家）和小锋（应用运维专家），
**我想要** 在WeCube中将已经存在的任务编排导出生成任务编排定义文件进行下载保存，
并且也能够上传并导入任务编排定义文件到WeCube中成为新的任务编排进行使用，
**从而** 实现对运维工作流程最佳实践的分享。

### AC01. 任务编排页面
**当** 小辉通过“协同 - 任务编排”菜单项进入任务编排页面时，
**那么** 他应当在页面的“编排名称”和“选择CI类型”列表右侧看到 **“导出编排”** 和 **“导入编排”** 动作按钮。

### AC02. 导出和下载
**假定** 小辉通过“协同 - 任务编排”菜单项进入任务编排页面，
**当** 他没有在“编排名称”列表中选择任何任务编排时，
**那么** 他应当在页面上看到“导出编排”动作按钮被禁用，

**当** 他在“编排名称”列表中选择了一个已有的任务编排时，
**那么** 他应当在页面上看到“导出编排”动作按钮被启用，
**当** 他点击“导出编排”按钮时，
**那么** 他应当可以通过浏览器将此任务编排导出的定义文件进行下载并保存。

### AC03. 上传和导入
**假定** 小辉通过“协同 - 任务编排”菜单项进入任务编排页面，
**当** 他点击“导入编排”按钮时，
**那么** 他应当可以指定一个本地存在的任务编排定义文件进行上传和导入，
并且他应当能够在“编排名称”列表中找到新导入的任务编排。然后用户可以预览，编辑，保存该编排。

## 备注
- 导出的任务编排定义文件可参考使用BPMN 2.0 XML格式。

### 2019-12-05 PBR
1. 编排的导出需要包含编排流程定义及编排节点的详细配置
1. 编排导入后，编排应为 **“草稿”** 状态，deploy编排时需要对编排的配置进行校验
1. 编排导入，同名编排不覆盖现有非草稿编排

## ETA: 
5 MD
## Owner:  
@gavin2lee

**Comment by irvinezhao** [comment]
备注：
- AC02-删除编排，状态位
- 导出编排格式
- 上传先预览，可编辑，再保存

**Comment by kanetz** [comment]
将任务编排的删除拆分到 #937
