### ISSUE TITLE
编排的权限控制

### ISSUE THREAD

**Issue by chaneyliu** [WeBankPartners/wecube-platform#352]
**描述您的需求**  
目前，编排设定完成后，所有有编排权限的人能看到并修改其他人设定的编排这样不利于权限保护。而现实场景需求是每个技术组别都可以设计编排并要求不允许别的组别人员来修改。

**预期行为** 
在编排保存按钮边上增加一个权限设定的按钮。点击权限设定按钮后，弹出一个对话框有一个编排使用权限和一个编排管理权限设定选择。使用权限将所有角色列出并多选设定；管理权限，根据编排设计人员所属的角色来选择，如果他只有一个角色，那么就是此角色，如果他有多个角色，也给出一个下拉框单选一个管理属主角色。未来在服务管理设计和编排任务执行时，可根据登录人员的角色来给出他所能使用的编排。编排的修改管理只能由其属主角色来完成。

**描述您考虑过的替代方案**  
无

**附加**
无

**Comment by irvinezhao** [comment]
角色 - 编排 - 关系 

> 关系有Own，Use两种， Own关系可以编辑/查看， 执行；Use关系只可执行。

注：1，编辑/查看流程为一个权限

**Comment by irvinezhao** [comment]
属主 - 编排 -> 1:n
执行 - 编排 -> m:n

**Comment by irvinezhao** [comment]
ETA: 3 md(BE) + 2 md(FE) @HoweChen @homiexie

**Comment by HoweChen** [comment]
@homiexie 

![image](https://user-images.githubusercontent.com/5387479/70681826-b2b56480-1cd7-11ea-9941-b0dd7b05a815.png)
新建编排
红框用来勾选
1. 属主（多个）
2. 使用者（多个）

新建编排的时候**必须选择属主**


编排编辑
只选择自己有**管理权限**的编排


新建编排任务执行
红框部分增加：只显示自己有**使用权限**的编排

**Comment by HoweChen** [comment]
@homiexie 
- [] 1. 更新编排与role-id 的关系
POST: platform/v1/process/{proc-id}/roles
body: 
```
{
    "mgmt": [
        "role1",
        "role2"
    ],
    "use": [
        "role3",
        "role4"
    ]
}
```

- [] 2. 获取对应角色的所有可管理编排

- [] 3. 获取对应角色的所有可运行编排

**Comment by HoweChen** [comment]
两个需要修改的接口

1. 编排管理的时候的查询所有编排，需要修改为
** 只查询得到自己拥有管理权限的编排 **

2. 编排运行的查询接口，需要修改为
** 只查询得到自己拥有运行权限的编排 **

**Comment by HoweChen** [comment]
@homiexie 

现在在`deploy`和 `draft` 的body里需要加入
```json
    "permissionToRole": {
        "mgmt": [
            1,
            2
        ],
        "USE": [
            3,
            4
        ]
    }
```
