### ISSUE TITLE
 建议提供脱机版本的安装部署包

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#355]
**描述您的需求**  
有较大更新进行编译的时候，会遇到依赖下不下来导致编译不成功。或者更换了环境会遇到node版本太低不能编译成功。

**预期行为**  
建议能进行脱机部署。比如提供打包了所有依赖的二进制文件方便Partner部署。

**描述您考虑过的替代方案**  

**附加**

**Comment by chaneyliu** [comment]
https://webankpartners.github.io/wecube-docs/standalone-mode-on-premises/
