### ISSUE TITLE
【框架2.0】插件注册功能 - 提供XML 解析结果查询接口

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#375]
**描述您的需求**  
前端需要查询接口去获取xml解析的结果。
就是 #285 中的以下接口：
 4.查询指定插件包的依赖分析
  5.查询指定插件包的菜单注入
  6.调整指定插件包的菜单顺序
  7.查询指定插件包的数据模型
  8.查询指定插件包的系统参数
  9.查询指定插件包的权限设定
  10.查询指定插件包的运行资源
  11.查询指定插件包的插件列表
  12.根据插件查询interface

**Comment by BenJaMiniature** [comment]
duplicate issue. check #398 for reference.
