### ISSUE TITLE
【框架2.0】插件包升级对已依赖资源的高危操作检查

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/wecube-platform#384]
**描述您的需求**  
插件包升级时，对依赖的已分配资源（MYSQL的增量升级SQL脚本）有结构性改动，需要对改动进行识别并提出警告，让用户预览和再次确认方可执行。

**预期行为**  
高危升级需要提醒用户预览和再次确认方可执行

**Comment by chaneyliu** [comment]
用户需执行必要备份，无需实现此功能。
