### ISSUE TITLE
【框架2.0】【后端】插件注册功能 - 注册包上传功能增强

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#386]
**描述您的需求**  
对新插件包进行注册的时候，前端提交新插件包给后端，后端接受到请求进行后续处理。
包括
1) 保存插件包到本地（现有）
2) 解压本地插件包（现有）
3 校验和解析插件xml（增强）
4) 上传插件镜像到S3（现有）
5) 存储S3镜像路径到数据库（增强）
5.1) 上传UI插件中的静态文件到ngnix服务器（可选） 
6) 存储插件包相关配置信息到数据库（增强）

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by gavin2lee** [comment]
395_workflow_2_0_refactor

**Comment by BenJaMiniature** [comment]
UI静态资源文件处理放在#437中处理

**Comment by BenJaMiniature** [comment]
UI静态资源文件处理放在 #437 中处理
