### ISSUE TITLE
【框架2.0】插件注册功能 - 创建销毁查询实例接口

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#402]
**描述您的需求**  
提供创建实例和销毁实例接口

19.创建插件实例（修改原有接口）
POST /packages/{package_id}/hosts/{host_ip}/ports/{port}/instance/launch
20.销毁插件实例(修改原有接口）
DELETE /packages/instances/{instance_id}

23.插件实例节点查询
(existing) GET /packages/instances
(existing) GET /packages/{package_id}/instances

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by haixinhuang** [comment]
19.创建插件实例（修改原有接口）
创建插件实例过程如下：
A. 检查插件包状态、插件注册状态、运行实例的目标主机IP有效性和端口的可用性 （修改） -- 已完成
B.如有mysql数据库，调用ResourceManagement创建数据库schema；然后从S3下载建表sql初始化数据库；（新增）  -- Todo
C.如有S3 bucket， 调用ResourceManagement创建bucket （新增）  -- Todo
D.从S3下载镜像包，推送到运行实例的目标主机，载入本地镜像库，调用ResourceManagement创建docker容器实例 （修改）  --  编码完成
E.如有UI，从S3下载UI package，部署到静态资源服务器。（新增）  -- Todo

**Comment by irvinezhao** [comment]
fixed in #476
