### ISSUE TITLE
【框架2.0】插件注册功能 - 获取可用母机、可用端口

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#403]
**描述您的需求**  
更新母机、端口及日志查询接口

- [x]  容器母机操作：   -- 在本issue中解决。
21.查询可用容器母机
(existing) GET /available-container-hosts
22.预分配端口
(existing) GET /hosts/{host-ip}/next-available-port

- [ ]  日志查询：   -- 已拆分到 #430  
24.插件实例日志查询接口
(existing) GET /packages/instances/log
25.插件实例日志详情查询接口
(existing) GET /packages/instances/{instance-id}/log-detail

**Comment by haixinhuang** [comment]
拆分为两个task：
1.容器母机操作 - 主要在当前资源管理的docker_container类型上加上对port属性的处理，此部分无依赖

2.日志查询 - 需要插件提供日志查询接口，应该是一个插件必须提供的标准接口，待讨论
