### ISSUE TITLE
用户未配置基础数据管理菜单权限时打开CI数据管理页面报错

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#408]
**描述您遇到的bug**  

用户未配置基础数据管理菜单权限时打开CI数据管理页面报错。菜单权限和数据查询权限应该分离。

![image](https://user-images.githubusercontent.com/17095701/66821312-d036ae00-ef74-11e9-9537-086d70a34e16.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
应该是权限部分的java代码里，菜单配置部分有遗漏。 @homiexie  敏敏帮忙看一下顺便学习java技术
