### ISSUE TITLE
调用插件购买机器失败，但是运行编排显示成功

### ISSUE THREAD

**Issue by DeliaDing123** [WeBankPartners/wecube-platform#416]
**描述您遇到的bug**  
调用插件购买机器失败，但是运行编排显示成功

**如何重现** 
在一台不能访问外网的机器上调用编排CREATE_VM_1016，查看Wecube编排执行结果

**预期行为** 
如果插件没有调用成功，Wecube应该正常显示错误。

**截图**  
![image](https://user-images.githubusercontent.com/46696471/66897637-fc603680-f029-11e9-806e-0aa6898f992c.png)
![image](https://user-images.githubusercontent.com/46696471/66897668-0aae5280-f02a-11e9-87de-98d92d90e026.png)

**附加**

**Comment by chaneyliu** [comment]
升级WeCube 2.x后解决。
