### ISSUE TITLE
【流程引擎2.0】 流程执行/预览页面

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#428]
**描述您的需求**  
![image](https://user-images.githubusercontent.com/17263271/67172562-642dcd00-f3ee-11e9-8d63-080dad4694fc.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by gavin2lee** [comment]
{
	"procDefId": "rFNPtQmk2Bo",
	"procDefKey": "Process_1xdh7qj",
	"procDefName": "GL-test-01",
	"procDefVersion": "1",
	"status": "deployed",
	"procDefData": null,
	"rootEntity": null,
	"flowNodes": [{
		"nodeId": "StartEvent_1",
		"nodeName": "",
		"nodeType": "startEvent",
		"nodeDefId": null,
		"status": null,
		"orderedNo": null,
		"procDefId": "rFNPtQmk2Bo",
		"procDefKey": "Process_1xdh7qj",
		"previousNodeIds": [],
		"succeedingNodeIds": ["Task_18nnofr"]
	}, {
		"nodeId": "Task_18nnofr",
		"nodeName": "T1",
		"nodeType": "subProcess",
		"nodeDefId": "rFNPtQxk2Bp",
		"status": null,
		"orderedNo": "1",
		"procDefId": "rFNPtQmk2Bo",
		"procDefKey": "Process_1xdh7qj",
		"previousNodeIds": ["StartEvent_1"],
		"succeedingNodeIds": ["EndEvent_0ed05er"]
	}, {
		"nodeId": "EndEvent_0ed05er",
		"nodeName": "",
		"nodeType": "endEvent",
		"nodeDefId": null,
		"status": null,
		"orderedNo": null,
		"procDefId": "rFNPtQmk2Bo",
		"procDefKey": "Process_1xdh7qj",
		"previousNodeIds": ["Task_18nnofr"],
		"succeedingNodeIds": []
	}]
}

**Comment by irvinezhao** [comment]
> {
> "procDefId": "rFNPtQmk2Bo",
> "procDefKey": "Process_1xdh7qj",
> "procDefName": "GL-test-01",
> "procDefVersion": "1",
> "status": "deployed",
> "procDefData": null,
> "rootEntity": null,
> "flowNodes": [{
> "nodeId": "StartEvent_1",
> "nodeName": "",
> "nodeType": "startEvent",
> "nodeDefId": null,
> "status": null,
> "orderedNo": null,
> "procDefId": "rFNPtQmk2Bo",
> "procDefKey": "Process_1xdh7qj",
> "previousNodeIds": [],
> "succeedingNodeIds": ["Task_18nnofr"]
> }, {
> "nodeId": "Task_18nnofr",
> "nodeName": "T1",
> "nodeType": "subProcess",
> "nodeDefId": "rFNPtQxk2Bp",
> "status": null,
> "orderedNo": "1",
> "procDefId": "rFNPtQmk2Bo",
> "procDefKey": "Process_1xdh7qj",
> "previousNodeIds": ["StartEvent_1"],
> "succeedingNodeIds": ["EndEvent_0ed05er"]
> }, {
> "nodeId": "EndEvent_0ed05er",
> "nodeName": "",
> "nodeType": "endEvent",
> "nodeDefId": null,
> "status": null,
> "orderedNo": null,
> "procDefId": "rFNPtQmk2Bo",
> "procDefKey": "Process_1xdh7qj",
> "previousNodeIds": ["Task_18nnofr"],
> "succeedingNodeIds": []
> }]
> }

大师这个数据结构对应哪一部分？
