### ISSUE TITLE
【框架2.0】插件注册功能 - WeCube提供插件日志查询

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#430]
这是 #403 的子需求。
在 #285 评论中提及：
日志查询：
24.插件实例日志查询接口
(existing) GET /packages/instances/log
25.插件实例日志详情查询接口
(existing) GET /packages/instances/{instance-id}/log-detail

这两个接口依赖插件是否提供日志查询接口，需要在 #420 插件规范中补充，并要求插件实现。

**Comment by irvinezhao** [comment]
有依赖，需要插件先提供日志查询接口。
