### ISSUE TITLE
【框架2.0】插件注册功能 - 表达式解析器

### ISSUE THREAD

**Issue by HoweChen** [WeBankPartners/wecube-platform#457]
需要根据用户的xml定义做插件注册时的 提供的`interface`当中的`inputParameter`或者`outputParameter`的`mappingEntityExpression` 表达式解析

**Comment by HoweChen** [comment]
例如，有一个六张表的关系，如图：

![image](https://user-images.githubusercontent.com/5387479/68260583-56c44400-0078-11ea-9ab9-fa37096ed91d.png)

则有以下三种情况：

1. 仅有 referenceTo 关系

```
A.a1-B.b2
A.a1-B.b2-C.c1
A.a1B.b2-D.d1
```

2. 仅有 referenceBy 关系

```
B~(a1)A.a2
D~(b2)B.id
D~(b2)B~(a1)A.a2
C~(b1)B~(a1)A.id
```

3. 混合的情况

```
A.a1-B~(id)E.e2
B~(a1)A.a2-F.f2
F~(a2).A.a1-B.b2-D.d2
```

**Comment by HoweChen** [comment]
更新设计以及入参出参

https://github.com/WeBankPartners/wecube-platform/issues/457#issuecomment-550100941

**Comment by irvinezhao** [comment]
@HoweChen :
11.11:
1. WeCube #457 通过 mock server 对服务进行单元测试，设计了五种场景，十个测试用例。测试过了9个
11.12：
1. WeCube #457 把剩下的一个测试用例跑完之后提交，然后给大师调用 . @gavin2lee

**Comment by HoweChen** [comment]
The PR has been merged, the issue can be closed.

**Comment by HoweChen** [comment]
# 链路式实战

## 无连接情况 

即无 reference to 或 reference by 的情况

`we-cmdb:system_design.code`，根ID值为`0001_0000000001`

语义：

1. 读取wecmdb:system_design 这张表的 ID 为 `0001_0000000001`的数据
2. 取出 `code` 这一列的值，结果为 `EDP`



`wecmdb:unit.key_name`，根 ID 为`0008_0000000003`

语义：

1. wecmdb:unit 这张表的 ID 为 `0008_0000000003`的数据
2. 取出 `key_name` 这一列的值，结果为`EDP-CORE_PRD-APP`



## 单连接的情况

### 单ReferenceTo

`wecmdb:subsys_design.system_design>wecmdb:system_design.code`, 根 ID 值为`0002_0000000006`

语义：

1. `wecmdb:subsys_design` 这张表的 ID 为 `0002_0000000006`的数据
2. 取出  `system_design` 这一列的值
3. 找出 2 所引用的来自`wecmdb:system_design`的记录
4. 找出 `code` 这一列的值，结果为 `EDP`

### 单ReferenceBy

`wecmdb:service_design~(service_design)wecmdb:invoke_design.key_name`, 根 ID 值为 `0004_0000000001`

语义：

1.  `wecmdb:invoke_design` 表中，列`service_design`引用了`wecmdb:service_design`的` ID`列（即后者被前者引用），其`ID`数据为`0004_0000000001`
2. 在1中找出这行数据，取出其中列名为`key_name`的数据，结果为有两个:
   1. EDP-ADMCORE-APP_SYNC_INVOC_EDP-CORE-APP-SER1
   2. EDP-ADMBATCH-APP_SYNC_INVOC_EDP-CORE-APP-SER1

##多连接情况

多连接的语义与单连接情况相同，下面给出具体例子

### 多 ReferenceTo 与多 ReferenceBy

`wecmdb:subsys.subsys_design>wecmdb:subsys_design.system_design>wecmdb:system_design.key_name`, 根 ID 值为 `0007_0000000001`, 返回值：`ECIF`



`wecmdb:subsys~(subsys)wecmdb:unit~(unit)wecmdb:running_instance.id`, 根 ID 值为`0007_0000000001`, 返回值为: `0015_0000000001`



### 混合情况

`wecmdb:subsys~(subsys)wecmdb:unit.unit_design>wecmdb:unit_design.subsys_design>wecmdb:subsys_design.key_name`, 根 ID 值为 `0007_0000000001`, 返回两行数据，提取出 `key_name`后两列数据相同：

1. ECIF-CORE
2. ECIF-CORE



`wecmdb:zone_design~(zone_design2)wecmdb:zone_link_design~(zone_link_design)wecmdb:zone_link.zone1>wecmdb:zone.key_name`, 根 ID 值为 `0023_0000000004`, 返回两行数据，提取出 `key_name`后两列数据为：

1. PRD-GZ1-MGMT
2. PRD-GZ1-PARTNERNET
