### ISSUE TITLE
【框架2.0】数据模型注册功能、插件注册功能支持动态模型增量

### ISSUE THREAD

**Issue by chaneyliu** [WeBankPartners/wecube-platform#467]
**描述您的需求**  
CMDB插件存在动态调整数据模型的可能性，目前插件注册后无法支持。
1、在插件的定义XML内的datamodel内增加一个声明同步模型的接口，WeCube解析时发现有这个接口声明，说明次插件存在动态调整模型的能力，需要在插件包配置的数据模型内增加一个同步数据的按钮。
![image](https://user-images.githubusercontent.com/54091452/67725483-88f0f880-fa1d-11e9-9657-4c713540682a.png)
2、用户点击次“同步数据模型”，WeCube调用CMDB插件声明的注册接口，并重新解析返回的数据模型定义XML，并与现有记录的数据模型做比较，校验数据模型中删除的部分被那些插件的参数所记录关联，返回一个提示确认，用户确认后更新数据模型，如果用户不确认，取消同步。
3、因为数据模型变更会影响已有插件的使用，模型更新后需要将被影响的插件变更为“未注册“状态。4、对于变更为”未注册”状态的插件，在插件注册交互中的数据模型参数，需要提供“.-”的输入编辑器，供用户编辑新的参数表达式，并提供使用现有的“保存”和”注册“将插件重新注册。

CMDB关联的issue为#376。

**预期行为**  
插件注册支持插件动态模型。

**描述您考虑过的替代方案**  

无
**附加**
无

**Comment by chaneyliu** [comment]
补充：5、对于注销插件和数据模型删除（编排中的定位规则使用到了数据模型的ref）影响编排的使用，需要识别出来，并在4的返回提示中一并返回，如果客户确认，需要将编排状态变更为“不可用”。

**Comment by irvinezhao** [comment]
4、对于变更为”未注册”状态的插件，在插件注册交互中的数据模型参数，需要提供“.-”的输入编辑器，供用户编辑新的参数表达式，并提供使用现有的“保存”和”注册“将插件重新注册。
@homiexie  这个要重新启用点杠大法了，在插件包是UNREGISTED状态时，允许用户编辑

**Comment by BenJaMiniature** [comment]
@chaneyliu 点击“同步数据模型”按钮是否需要前置条件？还是无条件允许点击？拉取的新数据模型数据是否无条件接受（基本校验通过的情况下）？
@irvinezhao 当插件恢复“未注册”状态之后，ui的静态资源列表在插件没有重新注册之前将不可用，这样对前端的使用有没有什么影响？

**Comment by homiexie** [comment]
> @chaneyliu 点击“同步数据模型”按钮是否需要前置条件？还是无条件允许点击？拉取的新数据模型数据是否无条件接受（基本校验通过的情况下）？
> @irvinezhao 当插件恢复“未注册”状态之后，ui的静态资源列表在插件没有重新注册之前将不可用，这样对前端的使用有没有什么影响？

@BenJaMiniature ui的静态资源列表在插件没有重新注册之前将不可用，对应菜单也不可见吧。否则页面会跳转到404

**Comment by BenJaMiniature** [comment]
> > @chaneyliu 点击“同步数据模型”按钮是否需要前置条件？还是无条件允许点击？拉取的新数据模型数据是否无条件接受（基本校验通过的情况下）？
> > @irvinezhao 当插件恢复“未注册”状态之后，ui的静态资源列表在插件没有重新注册之前将不可用，这样对前端的使用有没有什么影响？
> 
> @BenJaMiniature ui的静态资源列表在插件没有重新注册之前将不可用，对应菜单也不可见吧。否则页面会跳转到404

预期看不到菜单是正常的对吧？问个小问题，假如有用户在包状态修改为“未注册”前进入的菜单，包状态修改为“未注册”之后，用户再操作，这种场景怎么处理？
另外，数据模型参数处需要提供“.-”编辑器，这个操作是否调用已有的后台接口可以实现？
