### ISSUE TITLE
api-gateway 联调

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#520]
**描述您的需求**  

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
TODO:
1, 修改现有接口，所有接口都以/api 开头，haixin负责修改后端，Irving来修改 Nginx配置和前端代码
2，差一个自动注册插件接口 - haixin


@irvinezhao @haixinhuang

**Comment by irvinezhao** [comment]
关于API gateway的转发规则，现在统一为
core: /api/platform/v1/xxxx
其中 ```/api ```为前缀, ``` /platform```为资源提供方， ```/v1```为版本， ```/xxx```后续为操作或资源。
关于插件的路由规则，也需满足上述规则，如: ```/api/wecmdb/v1/xxxx```，为了满足上述规则，目前有两种方案：
a) 前端统一为所有的接口加上baseUrl = /api， 这样插件的接口通过前端发起就会带上/api前缀（为了Nginx代理转发），在插件不改动的情况下，需要api gateway接受后对属于插件的接口进行切割，把属于插件的接口请求中的/api前缀进行切割删除，进而继续进行后续转发操作。
b) 前端统一为所有的接口加上baseUrl = /api， 这样插件的接口通过前端发起就会带上/api前缀（为了Nginx代理转发），在api gateway不改动的情况下，需要插件对所有的接口加上/api前缀。

@gavin2lee @jordanzhangsz @haixinhuang @homiexie @nevinxie

**Comment by homiexie** [comment]
不建议要求插件加上/api，插件所有的接口调用都是用的portal的axios实例，可在portal统一加上就好了，api gateway把/api切割一下
