### ISSUE TITLE
【框架2.0】插件包上传支持Mac OS压缩的zip包

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#548]
**描述您遇到的bug**  
某用户使用Mac笔记本压缩插件包为zip包（Mac OS 压缩时自带__MACOSX目录），操作插件包上传功能时报错：No such file or directory。

**如何重现** 
使用Mac压缩插件包，然后上传插件包

**预期行为** 
上传成功。

**截图**  
![image](https://user-images.githubusercontent.com/22583258/68366985-8dc95100-016f-11ea-8ac9-a7c960332e9a.png)
![image](https://user-images.githubusercontent.com/22583258/68367270-455e6300-0170-11ea-9903-9729af1f0c5a.png)
![image](https://user-images.githubusercontent.com/22583258/68367301-5dce7d80-0170-11ea-9354-0cadeb422be0.png)

**Comment by BenJaMiniature** [comment]
fixed.
