### ISSUE TITLE
监控插件联调

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#559]
**描述您的需求**  

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by homiexie** [comment]
目前进度是页面显示正常，双语支持正常。待接口调用改造

**Comment by irvinezhao** [comment]
Update:
- 后端： 注册检查的数据模型模块有问题 @HoweChen 跟进，服务启停ok，容器可以拉起。
- 前端： 需要改进请求实例， @homiexie @pobu168 跟进。
