### ISSUE TITLE
提供插件列表API

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#593]
**描述您的需求**  
关于插件服务列表需要两个API接口：
1， 全量插件服务
2，根据定位规则筛选插件服务

第二个接口使用场景：在流程编排页面，配置节点的插件选择需要列出插件列表服务，此列表为根据定位规则过滤后的插件服务列表
![image](https://user-images.githubusercontent.com/17263271/68726130-7cfb5e00-05fb-11ea-94ca-dcd569a70237.png)

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
![image](https://user-images.githubusercontent.com/17263271/68727588-c9e13380-05ff-11ea-9959-847d04505a52.png)

getPluginServicesByEntityId(entityId)

以前的实现供参考：
Request URL: plugin/latest-online-interfaces?ci-type-id=20
Request Method: GET

Response：
```json
{
	"status": "OK",
	"message": "Success",
	"data": [{
		"id": 9,
		"name": "create",
		"serviceName": "qcloud-resource-management/Subnet Management/create",
		"serviceDisplayName": "qcloud-resource-management/Subnet Management/create",
		"path": "/v1/qcloud/subnet/create",
		"cmdbQueryTemplateId": 49,
		"filterStatus": "37",
		"resultStatus": "37",
		"inputParameters": null,
		"outputParameters": null
	}, {
		"id": 10,
		"name": "terminate",
		"serviceName": "qcloud-resource-management/Subnet Management/terminate",
		"serviceDisplayName": "qcloud-resource-management/Subnet Management/terminate",
		"path": "/v1/qcloud/subnet/terminate",
		"cmdbQueryTemplateId": 50,
		"filterStatus": "39",
		"resultStatus": "39",
		"inputParameters": null,
		"outputParameters": null
	}]
}
```

**Comment by BenJaMiniature** [comment]
Return PluginConfig with status ENABLED only. ignore those DISABLED ones.
