### ISSUE TITLE
前后端交互返回数据规范

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#610]
**描述您的需求**  
按讨论整理的前后端交互数据规范。

1、所有调用结果payload以json格式返回
2、json格式如下：
{
	"status": "OK",
	"message": "Success",
	"data": json字符串
}
3、status的包含如下四个状态
1> OK: 操作完成，正常返回
2> INFO: 由于业务逻辑限制，预期操作没有执行，但对系统没有影响，返回信息。如重复上传同名同版本的插件包。
3> WARN: 当前操作会关联影响到其他业务的。分两种场景返回，在message中区分。1)需要用户二次确认的操作，先返回WARN，用户确认之后才真正完成操作。2)直接执行操作，在message中返回信息告知用户影响了关联业务。
4> ERROR: 操作因为各种原因失败，在message中返回具体的错误原因
4、data字段的值原则上存储DTO的json字符串

具体的INFO和WARN场景由产品提供，后端后续做相应改进

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by BenJaMiniature** [comment]
与status状态对应的异常处理，初步设计如下：
OK: 正常返回
INFO: 抛WecubeCoreInfoException
WARN: 抛WecubeCoreWarnException
ERROR: 抛WecubeCoreErrorException

所有异常由GlobalExceptionHandler捕捉并返回

**Comment by chaneyliu** [comment]
已执行此规范定义。
