### ISSUE TITLE
数据模型表达式 - 实体引用从dash(-)修改为greater than(>)

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#672]
**描述您的需求**  
当前关于数据模型表达式中的使用到的符号的讨论，源于表达式中包名中可能包含符号“-”，而“-”在表达式中用作ref to，当插件包的包名中带了“-”的时候，前端无法正确切割表达式。
考虑到“-”等常用于域名和URL中，而插件的命名现在有用于约定包名做二级域名或者gateway中的context path，因此多方意见表示建议保留包名中的“-”。

目前达到的一致修改意见是原用于ref to 的dash(-)修改为greater than(>)。

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
PR: #674

**Comment by HoweChen** [comment]
目前的自动生成脚本在开发态发现一些不太友好的问题，先暂时还原回java文件。

**Comment by HoweChen** [comment]
PR: #684 issue can be closed.
