### ISSUE TITLE
创建和编辑系统参数时对参数值的更改不生效

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#673]
**描述您遇到的bug**  
同标题

**如何重现** 
1. 系统 - 系统参数 - 新增 - 保存
1. 系统 - 系统参数 - 编辑 - 保存

**预期行为** 
1. 系统参数值显示在列表中
1. 对系统参数值的更改正确生效

**截图**  
![image](https://user-images.githubusercontent.com/1160645/69315813-6b0c6180-0c72-11ea-999c-144468d47d9c.png)

![image](https://user-images.githubusercontent.com/1160645/69315848-811a2200-0c72-11ea-9e0d-7957e802fcba.png)

**附加**

**Comment by zhangsenfeng** [comment]
Fixed in #695
