### ISSUE TITLE
创建服务请求撤销已上传文件时不生效

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#677]
**描述您遇到的bug**  
同标题

**如何重现** 
任务 - Task Management

**预期行为** 
附件成功撤销 或 不提供此功能

**截图**  
![image](https://user-images.githubusercontent.com/1160645/69316840-9db75980-0c74-11ea-978d-8175a192233f.png)

![image](https://user-images.githubusercontent.com/1160645/69316867-a90a8500-0c74-11ea-811b-e7293c40d51d.png)

![image](https://user-images.githubusercontent.com/1160645/69316925-c50e2680-0c74-11ea-84d1-c3d7bb78b76e.png)

**附加**

**Comment by homiexie** [comment]
这里不是撤销已上传文件操作，而是关闭已上传文件显示列表。

**Comment by homiexie** [comment]
如果会造成用户混淆的话，请确认是否还需要展示已上传文件列表

**Comment by kanetz** [comment]
> 这里不是撤销已上传文件操作，而是关闭已上传文件显示列表。

如果是关闭已上传文件显示列表，是否应该提供关闭后再打开此列表的功能？

**Comment by kanetz** [comment]
> 如果会造成用户混淆的话，请确认是否还需要展示已上传文件列表

展示已上传文件列表的功能是必要的。

**Comment by irvinezhao** [comment]
> > 如果会造成用户混淆的话，请确认是否还需要展示已上传文件列表
> 
> 展示已上传文件列表的功能是必要的。

好的，那我们这个功能保留。

**Comment by homiexie** [comment]
> > 这里不是撤销已上传文件操作，而是关闭已上传文件显示列表。
> 
> 如果是关闭已上传文件显示列表，是否应该提供关闭后再打开此列表的功能？
个人认为没有必要，这并不是一个持久化数据，本身就是用户操作过程中的一个提示性信息
