### ISSUE TITLE
platform-core需要返回具体的可读的报错信息

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#682]
**描述您遇到的bug**  
在测试过程中，遇到以下报错不够明确：
1. 创建插件容器实例时，报错 "Failed to execute init.sql for schema[service_mgmt]" , 该报错不够具体，希望能将执行init.sql返回的报错抛出；
2.当WeCube未录入资源服务器时，创建插件容器实例报错空指针异常，希望能报错“找不到可用的资源服务器”；

**Comment by chaneyliu** [comment]
建议在v2.6.0版本修复
