### ISSUE TITLE
插件注册 - 插件包列表需返回是否为最新版本包信息

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#686]
**描述您的需求**  

isLatest = true/false
**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by BenJaMiniature** [comment]
现在PluginPackage里面有一个字段uploadTimestamp标记插件包上传的时间，有一个字段version表示插件包的版本号。
请确认上述两个信息是否可用/够用？该最新版本包信息的使用场景是什么？谢谢
@irvinezhao

**Comment by irvinezhao** [comment]
有这个 ```uploadTimestamp``` 够用了
