### ISSUE TITLE
插件名称建议统一格式&文字换行显示问题

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-platform#687]
**描述您遇到的bug**  
1.插件名称需统一格式，换号行问题， 见下图
![image](https://user-images.githubusercontent.com/14288907/69391789-d9066680-0d0e-11ea-984a-6cafbb60a152.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by nertonsong** [comment]
2.在选择“简体中文”下， 菜单中英文混杂， 见下图
![image](https://user-images.githubusercontent.com/14288907/69392385-d6a50c00-0d10-11ea-9a98-70b53f60bb25.png)

**Comment by irvinezhao** [comment]
> 2.在选择“简体中文”下， 菜单中英文混杂， 见下图
> ![image](https://user-images.githubusercontent.com/14288907/69392385-d6a50c00-0d10-11ea-9a98-70b53f60bb25.png)

目前，只有wecube原生菜单支持双语，插件的菜单只提供了单语言

**Comment by irvinezhao** [comment]
> **描述您遇到的bug**
> 1.插件名称需统一格式，换号行问题， 见下图
> ![image](https://user-images.githubusercontent.com/14288907/69391789-d9066680-0d0e-11ea-984a-6cafbb60a152.png)
> 
> **如何重现**
> 
> **预期行为**
> 
> **截图**
> 
> **附加**



> **描述您遇到的bug**
> 1.插件名称需统一格式，换号行问题， 见下图
> ![image](https://user-images.githubusercontent.com/14288907/69391789-d9066680-0d0e-11ea-984a-6cafbb60a152.png)
> 
> **如何重现**
> 
> **预期行为**
> 
> **截图**
> 
> **附加**

插件规范制定者 - @haixinhuang 新总

**Comment by irvinezhao** [comment]
换号行问题 - @homiexie @irvinezhao 着手修复
