### ISSUE TITLE
资源管理信息缺失

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-platform#689]
**描述您的需求**  
1.在资源管理->主机 列表中能看到各类资源的主机列表
![image](https://user-images.githubusercontent.com/14288907/69393386-f427a500-0d13-11ea-8580-544d3f69b0b7.png)

2.但在资源管理->实例 列表中， 实例信息跟主机无法对应
![image](https://user-images.githubusercontent.com/14288907/69393544-6f895680-0d14-11ea-87b9-e128f5c48f11.png)

1)容器实例， 未显示运行在哪个容器母机， 未显示容器实例ID；
2)数据库实例， 未显示db名称，未显示运行在哪个db服务器；
3) S3实例， 也需要显示桶信息等；

3.在插件注册页面中， 也需要显示插件使用到了资源实例的信息

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by zhangsenfeng** [comment]
在“ **实例** ”的“ **资源服务器** ”列展示的是“ **主机** ”的名称
![image](https://user-images.githubusercontent.com/26812573/69402182-087a9a80-0d32-11ea-9bf3-873562a05da6.png)
![image](https://user-images.githubusercontent.com/26812573/69402263-3bbd2980-0d32-11ea-9d65-b37a15104c16.png)

**Comment by irvinezhao** [comment]
> 在“ **实例** ”的“ **资源服务器** ”列展示的是“ **主机** ”的名称
> ![image](https://user-images.githubusercontent.com/26812573/69402182-087a9a80-0d32-11ea-9bf3-873562a05da6.png)
> ![image](https://user-images.githubusercontent.com/26812573/69402263-3bbd2980-0d32-11ea-9d65-b37a15104c16.png)

这个过滤能用不？
![image](https://user-images.githubusercontent.com/17263271/69411433-ef7ce400-0d47-11ea-97f2-ebd33b303924.png)

**Comment by zhangsenfeng** [comment]
后端数据没有返回，麻烦 @jordanzhangsz 帮忙定位
![image](https://user-images.githubusercontent.com/26812573/69416867-8f3f6f80-0d52-11ea-85e4-02d34ae88e83.png)
![image](https://user-images.githubusercontent.com/26812573/69417055-e7767180-0d52-11ea-8668-11e2853cebb0.png)

url:
http://localhost:3000/platform/resource/items/retrieve

**Comment by irvinezhao** [comment]
issue fixed
