### ISSUE TITLE
wecmdb插件同步数据模型报404错误

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#715]
**描述您遇到的bug**  
wecmdb插件未注册时，同步数据模型报404错误，错误原因不明确。
![image](https://user-images.githubusercontent.com/17095701/69510317-6f3cc580-0f77-11ea-87bf-627d5455ef36.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed
