### ISSUE TITLE
插件创建运行节点成功后页面仍显示原可用端口和创建按钮

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#716]
**描述您遇到的bug**  
插件创建运行节点成功后页面仍显示原可用端口和创建按钮。
![image](https://user-images.githubusercontent.com/17095701/69510444-0275fb00-0f78-11ea-9244-fd38ada3af9c.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
是允许创建多个运行节点的吧
