### ISSUE TITLE
插件服务注册页面输入框显示不完整

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#720]
**描述您遇到的bug**  
插件服务注册页面输入框显示不完整。

![image](https://user-images.githubusercontent.com/17095701/69511650-fd1aaf80-0f7b-11ea-96ca-727f8ba8d006.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
#687 会在这个issue中修复
