### ISSUE TITLE
插件服务注册的对象类型和属性用表名列名为列表选项不易理解

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#721]
**描述您遇到的bug**  
插件服务注册的对象类型和属性用表名列名为列表选项不易理解。应该用CI类型和属性的名称或编码。

![image](https://user-images.githubusercontent.com/17095701/69511761-6d293580-0f7c-11ea-845a-85ad78cc0457.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
为了保持链路式所见即所得，暂时没有修复计划
