### ISSUE TITLE
插件服务注册属性不可配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#722]
**描述您遇到的bug**  
插件服务注册属性不可配置。
1. 配置插件服务注册属性，选择entity，输入"~"报错
2. 配置插件服务注册属性，选择entity，输入"."， 有时无属性选择返回， 返回的属性无guid属性可选。

![image](https://user-images.githubusercontent.com/17095701/69512043-76ff6880-0f7d-11ea-9d5d-730fb5e54602.png)
![image](https://user-images.githubusercontent.com/17095701/69512195-11f84280-0f7e-11ea-9d67-1d6dcfd84df1.png)
![image](https://user-images.githubusercontent.com/17095701/69512265-584da180-0f7e-11ea-8f37-771acee026c5.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@homiexie  宝贝 是不是也是链路式一起的？ 如果是的话 顺手把这个臭虫一起弄了吧
