### ISSUE TITLE
删除插件问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#723]
**描述您遇到的bug**  
1. 删除没有二次确认提示
2. 正在运行的插件不应允许删除成功
3. 删除插件后菜单没有自动刷新

![image](https://user-images.githubusercontent.com/17095701/69512423-f2154e80-0f7e-11ea-8109-d41b8721f34b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed
