### ISSUE TITLE
插件服务注册未配置对象和属性仍然可以保存注册成功

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#738]
**描述您遇到的bug**  
插件服务注册未配置对象和属性仍然可以保存注册成功，应做校验。
![image](https://user-images.githubusercontent.com/17095701/69530594-40414680-0fad-11ea-93ca-de46e12a0fe2.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by BenJaMiniature** [comment]
@yolanda0209 对于cmdb的confirmation接口，目标对象类型可以为空，因此目前保存和注册都不校验entity是否为空。
注册接口增加对接口参数的校验，声明为required的属性如果没有赋值则返回注册错误。

**Comment by BenJaMiniature** [comment]
对于cmdb的confirmation接口，目标对象类型可以为空，因此目前保存和注册都不校验entity是否为空。
注册接口增加对接口参数的校验，声明为required的属性如果没有赋值则返回注册错误。
Fixed
