### ISSUE TITLE
插件不应注册重复菜单

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#746]
**描述您遇到的bug**  
插件不应注册重复菜单。
![image](https://user-images.githubusercontent.com/17095701/69594009-ef296500-1035-11ea-8f82-1a7256427878.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by BenJaMiniature** [comment]
与 @irvinezhao 和 @chaneyliu 讨论结果，考虑到相同的插件包可以同时注册两个版本，过渡期菜单显示两个版本的菜单并集，同名的菜单显示最新版本。
如cmdb:v1有菜单：cmdb:v1:menu1，cmdb:v1:menu2，
cmdb:v2有菜单cmdb:v2:menu1,cmdb:v2:menu3，
那么插件cmdb的菜单的集合为cmdb:v1:menu2, cmdb:v2:menu1, cmdb:v2:menu3。

**Comment by BenJaMiniature** [comment]
由于相关代码在如下PR中改动比较大https://github.com/WeBankPartners/wecube-platform/pull/705，issue在PR 705合并之后再进去修改。

**Comment by BenJaMiniature** [comment]
考虑到相同的插件包可以同时注册两个版本，过渡期菜单显示两个版本的菜单并集，同名的菜单显示最新版本。
如cmdb:v1有菜单：cmdb:v1:menu1，cmdb:v1:menu2，
cmdb:v2有菜单cmdb:v2:menu1,cmdb:v2:menu3，
那么插件cmdb的菜单的集合为cmdb:v1:menu2, cmdb:v2:menu1, cmdb:v2:menu3。

Fixed
