### ISSUE TITLE
插件服务注册配置属性参数时输入“.”或“~”不触发列表选项

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#748]
**描述您遇到的bug**  
插件服务注册配置属性参数时输入“.”或“~”不触发列表选项。
![image](https://user-images.githubusercontent.com/17095701/69595329-30237880-103a-11ea-908c-e3011bbb3c4a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
#722 在这个issue中修复了
