### ISSUE TITLE
插件服务注册属性未支持枚举属性的code返回

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#749]
**描述您遇到的bug**  
插件服务注册属性未枚举属性的code返回，单选枚举应返回code， 多选枚举应返回code列表。当前插件返回单选枚举的是id。

![image](https://user-images.githubusercontent.com/17095701/69595954-ff444300-103b-11ea-978e-3d50029ac21b.png)

![image](https://user-images.githubusercontent.com/17095701/69692169-2e29ea00-110c-11ea-8ee6-a4fbd8304377.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
Jordan fixed, please help verify @yolanda0209
