### ISSUE TITLE
插件服务注册的操作配置顺序问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#751]
**描述您遇到的bug**  
插件服务注册的操作配置顺序问题： 如腾讯云vpc的操作，有时create在前，有时terminate在前。
![image](https://user-images.githubusercontent.com/17095701/69596595-1126e580-103e-11ea-9647-938ca26c3f2a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@HoweChen  豪哥帮忙看看这个返回是不是排序发生变化了

**Comment by HoweChen** [comment]
The bug has been fixed, the issue can be closed.
