### ISSUE TITLE
支持插件升级

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-platform#762]
**描述您的需求**  
支持插件升级：
创建插件实例时，如果是已有旧版本的插件实例在运行中：

- [x] 需要支持新创建的实例使用旧实例的数据库；

- [ ] 需要执行upgrade.sql

**Comment by irvinezhao** [comment]
subtask 1 done by @haixinhuang

**Comment by chaneyliu** [comment]
已在 #1809中解决。
