### ISSUE TITLE
插件服务注册未配置的属性保存错误的值

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#763]
**描述您遇到的bug**  
插件服务注册未配置的属性保存错误的值，未配置的属性值应该是wecmdb:network_zone 而不是qcloud
![image](https://user-images.githubusercontent.com/17095701/69612645-12bad280-106b-11ea-9f20-a2247101ee3f.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
#760 应该是由这个问题引起的入参错误，现在760已经修复
