### ISSUE TITLE
插件服务注册的目标对象类型和属性列表未排序

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#766]
**描述您遇到的bug**  
插件服务注册的目标对象类型和属性列表未排序。
![image](https://user-images.githubusercontent.com/17095701/69616157-13566780-1071-11ea-89ff-72c8fbf5b2ed.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
插件服务注册的目标对象类型 已排序

**Comment by haixinhuang** [comment]
@HoweChen 说已经fixed，查看代码也已有该排序逻辑。请 @yolanda0209  验证
