### ISSUE TITLE
任务编排查询和新建流程不对

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#778]
**描述您遇到的bug**  
任务编排查询和新建流程不对：
1. 查询已执行过的任务，页面显示的是任务流程待执行，而不是之前已执行过的状态
2. 新建任务，页面显示的是已执行过的状态而不是待执行的任务流程
![image](https://user-images.githubusercontent.com/17095701/69691704-c7580100-110a-11ea-8cea-af202e989f17.png)

![image](https://user-images.githubusercontent.com/17095701/69691634-9f689d80-110a-11ea-9d6c-9798d3bb3151.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
issue fixed in PR #781
