### ISSUE TITLE
插件可选参数未配置时插件调用失败，插件需支持配置空参数

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#782]
**描述您遇到的bug**  
可选参数未配置时插件调用失败。如create VPC的id未配置属性时执行流程编排报错。可选参数未配置时应该调用插件成功。

![image](https://user-images.githubusercontent.com/17095701/69773175-077fb800-11cd-11ea-8b34-0e66e45877d8.png)
![image](https://user-images.githubusercontent.com/17095701/69773227-3564fc80-11cd-11ea-9677-dabe4267bafe.png)
![image](https://user-images.githubusercontent.com/17095701/69773254-4a419000-11cd-11ea-9d7d-2eb70cb82605.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@BenJaMiniature  Ben，这个可能要支持optional的case

**Comment by BenJaMiniature** [comment]
经讨论，前端传递的数据模型表达式中作处理。@irvinezhao

**Comment by irvinezhao** [comment]
数据模型提供的属性中加上两个选项 ```.ALL```,```.NONE```, 这样可行吗 @HoweChen

**Comment by irvinezhao** [comment]
加了 ```.NONE```
