### ISSUE TITLE
编排任务插件列表未根据定位规则过滤

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#783]
**描述您遇到的bug**  
编排任务插件列表未根据定位规则过滤。
![image](https://user-images.githubusercontent.com/17095701/69701675-68a18000-1128-11ea-8276-e9a9f076f0af.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by BenJaMiniature** [comment]
Add a new interface for filtering by package name and entity name.

    @GetMapping("/plugins/interfaces/package/{package-name}/entity/{entity-name}/enabled")
