### ISSUE TITLE
编排流程的任务未命名时流程图节点无默认名称

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#784]
**描述您遇到的bug**  
编排流程的任务未命名时流程图节点无默认名称。
![image](https://user-images.githubusercontent.com/17095701/69701766-aacac180-1128-11ea-9d6f-46eac1f26683.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed in #788
