### ISSUE TITLE
插件服务注册属性配置比较长时鼠标没有聚焦到行尾

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#789]
**描述您遇到的bug**  
插件服务注册属性配置比较长时鼠标没有聚焦到行尾，需要手动拉到行尾才能配置下一项。
![image](https://user-images.githubusercontent.com/17095701/69704871-5414b600-112f-11ea-92c8-d756871f4c18.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
操作时不需要聚焦到行尾，在任何地方输入都可以的，不影响表达式的拼接
