### ISSUE TITLE
配置插件时页面不可配置关联参数

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#797]
**描述您遇到的bug**  
配置插件时页面不可配置关联参数，如配置确认接口需要配置关联参数的来源，但是配置插件时页面不可配置。
![image](https://user-images.githubusercontent.com/17095701/69714349-36e8e300-1141-11ea-8712-cf5684a56153.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
Request URL: http://111.230.161.237:19090/platform/v1/process/definitions/rJ59u5RV2Bs/tasknodes/briefs
Request Method: GET

![image](https://user-images.githubusercontent.com/17263271/69775222-123d4b80-11d3-11ea-936e-14e3ce948df2.png)

没有数据返回 @gavin2lee

**Comment by gavin2lee** [comment]
这里的需求和实现，大家都清楚了没有？
@irvinezhao 
@yolanda0209
