### ISSUE TITLE
上传新的qcloud插件后旧的已注册qcloud插件不可用

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#803]
**描述您遇到的bug**  
上传新的qcloud插件后旧的已注册qcloud插件不可用。执行编排插件参数获取不到原来已注册的插件接口属性值。
![image](https://user-images.githubusercontent.com/17095701/69770546-612fb480-11c4-11ea-995c-7d30f0e7eefc.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@BenJaMiniature  Ben 帮忙看看？

**Comment by BenJaMiniature** [comment]
@irvinezhao 跟超哥和Yolanda讨论结果是新插件需要重新配置，这个不做代码修改。 @yolanda0209 @chaneyliu
