### ISSUE TITLE
数据模型服务代码重构优化

### ISSUE THREAD

**Issue by HoweChen** [WeBankPartners/wecube-platform#822]
现在数据模型服务的代码冗余部分较多，需要进行重构优化

**Comment by HoweChen** [comment]
@homiexie 

相关接口

1. 用户创建
POST /v1/users/create

2. 用户获取
GET /v1/users/retrieve

3. 删除用户
DELETE /v1/users/{user-id}/delete

4.角色创建
POST /v1/roles/create

5. 角色获取
GET /v1/roles/retrieve

6. 角色删除
DELETE /v1/roles/{role-id}/delete

7. 根据用户名获取其角色
GET /v1/users/{user-name}/roles

8. 根据角色id获取用户
GET /v1/roles/{role-id}/users

9. 给用户下发角色
POST /v1/roles/{role-id}/users/grant

10. 收回用户的角色
DELETE /v1/roles/{role-id}/users/revoke

**Comment by homiexie** [comment]
> @homiexie
> 
> 相关接口
> 
> * [ ]  1. 用户创建
>   POST /v1/users/create
> * [ ]  2. 用户获取
>   GET /v1/users/retrieve
> * [ ]  3. 删除用户
>   DELETE /v1/users/{user-id}/delete
> * [ ]  4. 角色创建
>   POST /v1/roles/create
> * [ ]  5. 角色获取
>   GET /v1/roles/retrieve
> * [ ]  6. 角色删除
>   DELETE /v1/roles/{role-id}/delete
> * [ ]  7. 根据用户名获取其角色
>   GET /v1/users/{user-name}/roles
> * [ ]  8. 根据角色id获取用户
>   GET /v1/roles/{role-id}/users
> * [ ]  9. 给用户下发角色
>   POST /v1/roles/{role-id}/users/grant
> * [ ]  10. 收回用户的角色
>   DELETE /v1/roles/{role-id}/users/revoke
这些接口为什么在这个issue里？

**Comment by HoweChen** [comment]
The issue can be shut down temporarily.
