### ISSUE TITLE
插件服务注册参数的属性值和目标对象类型不匹配

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#824]
**描述您遇到的bug**  
插件接口属性的初始值是“qcloud:”, 选择目标对象类型为resource_set, character_set参数的属性类型为Context保存后 ， 再切换属性类型为entity时参数的属性值和目标对象类型不匹配。
![image](https://user-images.githubusercontent.com/17095701/69786133-c26f7c00-11f4-11ea-912c-b2c88ce49427.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
@homiexie 我记得你修好了？
