### ISSUE TITLE
配置插件的关联参数确认后再次打开配置关联参数不回显

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#842]
**描述您遇到的bug**  
配置插件的关联参数确认后再次打开配置关联参数不回显。
![image](https://user-images.githubusercontent.com/17095701/69838123-1a59c180-128d-11ea-85e6-97daadaafdd8.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed
