### ISSUE TITLE
任务编排删除任务后被删除的任务仍然提交保存

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#843]
**描述您遇到的bug**  
任务编排删除任务后被删除的任务仍然提交保存，导致流程任务错误。
![image](https://user-images.githubusercontent.com/17095701/69838343-2003d700-128e-11ea-87f0-b90d1dfb4479.png)
![image](https://user-images.githubusercontent.com/17095701/69838381-475aa400-128e-11ea-9f2d-6ad9e7d5c0d1.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed in #892
