### ISSUE TITLE
插件包和服务状态控制问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#845]
**描述您遇到的bug**  

1. 正在运行的插件包可以注销成功，应做校验。

2. 插件包已注销，但是该插件包下已注册的服务仍然可以在插件配置进行配置。

3. 新插件包上传注册后会导致服务列表重复，应该只有最新版本的插件服务可用。

![image](https://user-images.githubusercontent.com/17095701/69839317-f3ea5500-1291-11ea-93f6-f208ff26bb6d.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by BenJaMiniature** [comment]
1、有实例运行时，插件包不可以注销/删除；否则报错。
2、正常注销/删除插件包时，关联的插件服务也会被disable。
3、只有注册过的插件包的ENABLED的插件服务可以出现在流程编排列表中。
4、同名不同版本的两个已注册的插件包，返回插件服务列表时同名的插件服务只返回最新版本的。
