### ISSUE TITLE
wecmdb插件的服务注册页面应显示服务接口的配置参数

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#848]
**描述您遇到的bug**  
wecmdb插件的服务注册页面应显示服务接口的配置参数。现在需要点击一下“CI Data Confirmation”才展示该接口的配置参数。
![image](https://user-images.githubusercontent.com/17095701/69839511-c4881800-1292-11ea-8d62-cb6807c1b706.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
#824 在这个issue中修复，改为当只有一个服务时默认显示当前服务，有多个服务时需要选择一个
