### ISSUE TITLE
CMDB插件同步数据模型或确认注册插件包后页面没有刷新

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#853]
**描述您遇到的bug**  

1。CMDB插件同步数据模型后会导致插件包状态为UNREGISTERED，但是页面上又没有出现确认tab供注册，需要刷新页面才能确认注册。
2. CMDB插件确认注册插件包后，页面没刷新，仍然可以再次进行确认。
![image](https://user-images.githubusercontent.com/17095701/69846998-c95bc480-12b0-11ea-8ba4-f6fc0e8d563a.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed
