### ISSUE TITLE
编排任务查询返回的流程内容和编排不一致

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#860]
**描述您遇到的bug**  
编排任务查询返回的流程和编排不一致： 查询“销毁VPC”编排，页面显示的流程却是创建VM编排的内容。
![image](https://user-images.githubusercontent.com/17095701/69857198-5c552880-12ca-11ea-85c8-9ed277b55b8e.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by homiexie** [comment]
无法复现

**Comment by homiexie** [comment]
没有复现
