### ISSUE TITLE
树的显示应该只有HOST，不应该有IP节点

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#867]
**描述您遇到的bug**  
![image](https://user-images.githubusercontent.com/17263271/69863649-5108f980-12d8-11ea-9a58-33f75fef5bb5.png)
![image](https://user-images.githubusercontent.com/17263271/69863711-6bdb6e00-12d8-11ea-805c-11026107f8f8.png)

Request URL: http://111.230.161.237:19090/platform/v1/process/definitions/rJcLYP4x2Ey/preview/entities/0015_0000000004
Request Method: GET

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by gavin2lee** [comment]
![image](https://user-images.githubusercontent.com/7447034/69939135-0e366400-151a-11ea-8145-cd397e8c2847.png)

**Comment by gavin2lee** [comment]
![image](https://user-images.githubusercontent.com/7447034/69939165-20b09d80-151a-11ea-84e5-2e83f69ad8fa.png)

**Comment by gavin2lee** [comment]
{"status":"OK","message":"Success","data":[{"packageName":"wecmdb","entityName":"resource_instance","dataId":"0015_0000000004","id":"wecmdb:resource_instance:0015_0000000004","previousIds":[],"succeedingIds":["wecmdb:ip_address:0017_0000000003"]},{"packageName":"wecmdb","entityName":"ip_address","dataId":"0017_0000000003","id":"wecmdb:ip_address:0017_0000000003","previousIds":["wecmdb:resource_instance:0015_0000000004"],"succeedingIds":[]}]}

**Comment by gavin2lee** [comment]
@yolanda0209 
@irvinezhao 
監控插件配置了IP，這裏顯示IP節點，是正常的
