### ISSUE TITLE
新建任务编排，confirm接口插件配置没有entity列表

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#880]
**描述您遇到的bug**  
新建任务编排，confirm接口插件配置没有entity列表。
![image](https://user-images.githubusercontent.com/17095701/69938197-9e26de80-1517-11ea-8bfc-478d69f507bc.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
saveDraft之后没有节点信息返回 @gavin2lee

**Comment by gavin2lee** [comment]
fixed
