### ISSUE TITLE
服务注册参数解析异常

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#887]
**描述您遇到的bug**  
服务注册参数解析异常
![image](https://user-images.githubusercontent.com/17095701/70017151-5a86b000-15bd-11ea-8f68-081a094e7250.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by BenJaMiniature** [comment]
在@PrePersist创建的字符串id中，有可能存在部分属性有空格的情况，当前修改策略是把空格替换为下划线"_"

**Comment by BenJaMiniature** [comment]
1、插件定义xml中action的值不可以带空格；
2、wecube中生成插件相关id时对id中带有的空格替换为下划线_
