### ISSUE TITLE
表core_ru_task_node_exec_param字段param_data_value长度不够长导致执行流程失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#903]
**描述您遇到的bug**  

![image](https://user-images.githubusercontent.com/17095701/70039391-d7814c00-15f4-11ea-9365-1d978d35d39b.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by gavin2lee** [comment]
fixed
