### ISSUE TITLE
支持审批类 常量输入

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#910]
**描述您的需求**  

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by gavin2lee** [comment]
"paramInfos": [
        {
          "bindNodeId": "string",
          "bindParamName": "string",
          "bindParamType": "string",
          "bindType": "string",
          "bindValue": "string",
          "id": "string",
          "nodeId": "string",
          "paramName": "string"
        }
      ]
