### ISSUE TITLE
自定义业务id改进

### ISSUE THREAD

**Issue by BenJaMiniature** [WeBankPartners/wecube-platform#916]
**描述您的需求**  
当前插件包相关的自定义业务id存在不够精简的问题，根据业务把id精简。

| Domain | ID Rule | Special Handling | Confirmed |
|--------|---------|------------------|-----------|
| PluginPackage | packageName + packageVersion | | Y |
| PluginPackageDependency | packageName + packageVersion + dependencyPackageName + dependencyPackageVersion | |  N |
| PluginPackageMenu | packageName + packageVersion + category + code |  |  N |
| PluginPackageDataModel | packageName + dataModelVersion |  |  N |
| PluginPackageEntity |  packageName + dataModelVersion + entityName |  |  N |
| PluginPackageAttribute |  packageName + dataModelVersion + entityName + attributeName |  |  N |
| SystemVariable | packageName + packageVersion + variableName  |  |  N |
| PluginPackageAuthority | packageName + packageVersion + roleName + menuCode | |  N |
| PluginPackageRuntimeResourcesDocker | packageName + packageVersion + imageName |  |  N |
| PluginPackageRuntimeResourcesMysql | packageName + packageVersion + schemaName |  |  N |
| PluginPackageRuntimeResourcesS3 | packageName + packageVersion + bucketName |  |  N |
| PluginConfig  | packageName + packageVersion + pluginConfigName |  |  N |
| PluginConfigInterface | packageName + packageVersion + pluginConfigName + action | |  N |
| PluginConfigInterfaceParameter | packageName + packageVersion + pluginConfigName + action + type(I/O) + parameterName| I for Input and O for Output |  N |
| PluginPackageResourceFile | UUID |  |  N |
| PluginInstance | packageName + packageVersion + containerName + host + port |  |  N |
| PluginMysqlInstance | packageName + packageVersion + schemaName + username | |  N |
| MenuItem | parentCode + menuCode |  |  N |
| ResourceServer | resourceServerName + resourceServerType |  |  N |
| ResourceItem | resourceServerName + resourceServerType + resourceItemName + resourceItemType |  |  N |

**预期行为**  

**描述您考虑过的替代方案**  

**附加**

**Comment by irvinezhao** [comment]
SystemVariable | packageName + packageVersion + variableName + GLOBAL/packageName
-- | --


这个```GLOBAL/packageName``` 应该不需要，插件声明的系统参数都是GLOBAL的，如果是本插件包的应该不需要声明

**Comment by BenJaMiniature** [comment]
有道理，已更新。
| Domain | ID Rule | Special Handling | Confirmed |
|--------|---------|------------------|-----------|
| SystemVariable | packageName + packageVersion + variableName  |  |  N |

**Comment by BenJaMiniature** [comment]
相关改动已在下面PR中完成。
https://github.com/WeBankPartners/wecube-platform/pull/1044

| Domain | ID Rule | Special Handling | Confirmed |
|--------|---------|------------------|-----------|
| PluginPackage | packageName + packageVersion | | Y |
| PluginPackageDependency | packageName + packageVersion + dependencyPackageName + dependencyPackageVersion | |  Y |
| PluginPackageMenu | packageName + packageVersion + category + code |  |  Y |
| PluginPackageDataModel | "DataModel" + packageName + dataModelVersion |  |  Y |
| PluginPackageEntity |  packageName + dataModelVersion + entityName |  |  Y |
| PluginPackageAttribute |  packageName + dataModelVersion + entityName + attributeName |  |  Y |
| SystemVariable | source + scope + name |  |  Y |
| PluginPackageAuthority | packageName + packageVersion + roleName + menuCode | |  Y |
| PluginPackageRuntimeResourcesDocker | "Docker" + packageName + packageVersion + imageName |  |  Y |
| PluginPackageRuntimeResourcesMysql | "MySql" + packageName + packageVersion + schemaName |  |  Y |
| PluginPackageRuntimeResourcesS3 | "S3" + packageName + packageVersion + bucketName |  |  Y |
| PluginConfig  | packageName + packageVersion + pluginConfigName + registerName |  |  Y |
| PluginConfigInterface | pluginConfigId + action + targetEntity | |  N |
| PluginConfigInterfaceParameter | configInterfaceId + type + name |  N |
| PluginPackageResourceFile | UUID |  |  N |
| PluginInstance | containerName + host + port |  |  N |
| PluginMysqlInstance | pluginPackageId + schemaName + username | |  N |
| MenuItem | parentCode + menuCode |  |  N |
| ResourceServer | host + resourceServerType + resourceServerName |  |  N |
| ResourceItem | resourceServerId + resourceItemType + resourceItemName |  |  N |

如果有issue另外再创建issue修改。
