### ISSUE TITLE
插件服务注册配置好目标对象类型后直接注册没有提交entity进行保存

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#918]
**描述您遇到的bug**  
插件服务注册配置好目标对象类型后直接注册没有提交entity进行保存。

![image](https://user-images.githubusercontent.com/17095701/70117837-6186ee80-16a1-11ea-821f-5c26604123ff.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
这个貌似好了， @yolanda0209 确认一下还存在吗？
