### ISSUE TITLE
提供接口给插件或者集成组件同步用户

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-platform#919]
**描述您的需求**  
1.同步用户
(1)调用方式：
String url = appSyncUserApi + "?appid="+appId+"&nonce="+randomNum+"&timestamp="+times+"&signature="+signature;
(2)参数说明：
Appid： E申请id
randomNum：随机数  
times：时间戳 
appToken：Token 
signature：将appId+randomNum+times进行MD5加密生成tmp，再用tmp+appToken生成
(4)返回样例
```{
    "Code": "0",
	"params":[
        {	
			"oid":"xxx",
			"englishName":"kantlin",
			"chineseName":"xxx",
			"position":"xxx",
			"status":"xxx"
        }
    ]
}
```

---------------------
## WeCube Platform:
(1)调用方式：
Request URL: platform/v1/users/retrieve
Request Method: GET
(2)参数说明：
N/A
(3) 返回样例：
```
{
    "status": "OK",
    "message": "success",
    "data": [
        {
            "createdBy": null,
            "updatedBy": null,
            "createdTime": "2019-12-09T07:32:16.000+0000",
            "updatedTime": null,
            "id": 2,
            "username": "umadmin",
            "password": "$2a$10$XH7kL/aIjCKwZZ2CXd5Nk.dFxyP4UubHa7vqekT1IYB1dX./0Hr8m",
            "active": true,
            "blocked": null,
        }
    ]
}


```
![image](https://user-images.githubusercontent.com/17263271/72042648-14beb500-32ea-11ea-84ca-631f74a8b71f.png)

TODO:

- [ ] 不要暴露密码

- [ ] 角色要有username和localUsername

**Comment by gavin2lee** [comment]
新的重构，返回的参数有变化。
{
    "status": "OK",
    "message": "success",
    "data": [
        {
            "id": "ff8081816fa35b9a016fa36851630001",
            "username": "jim",
            "password": null,
            "nativeName": "吉米",
            "title": "总经理",
            "emailAddr": "aaa@163.com",
            "officeTelNo": "0755-88888888",
            "cellPhoneNo": "15322228888",
            "department": "分布式科技发展部",
            "englishName": "jimgreen",
            "active": true,
            "blocked": false,
            "deleted": false,
            "roles": []
        }
    ]
}

**Comment by irvinezhao** [comment]
close this and open new in #1520
