### ISSUE TITLE
使用应用部署功能-如何部署应用系统服务

### ISSUE THREAD

**Issue by hewenjian123** [WeBankPartners/wecube-platform#92]
**描述您遇到的bug**  
使用应用部署功能-如何部署应用系统服务？
打开应用部署-部署任务无下拉选项，请问部署一个应用服务的流程是怎样的？是先编排服务吗？

**如何重现** 
打开应用部署-部署任务无下拉选项

**预期行为** 

**截图**  
<img width="960" alt="应用部署" src="https://user-images.githubusercontent.com/13130132/63638597-fbabc380-c6bc-11e9-99f5-ba93f0614213.png">

**附加**

**Comment by irvinezhao** [comment]
刚和@kanetz 桐哥沟通过， 任务先移到1.3 @DeliaDing123 @nevinxie @chaneyliu
