### ISSUE TITLE
新建编排的任务节点配置插件时不应缓存前一个任务节点的配置

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#925]
**描述您遇到的bug**  
新建编排的任务节点配置插件时不应缓存前一个任务节点的配置。
![image](https://user-images.githubusercontent.com/17095701/70131498-5cd03380-16bd-11ea-8355-82d05a37e9dd.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by irvinezhao** [comment]
fixed
