### ISSUE TITLE
删除任务编排

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#937]
## 背景和价值
**作为** 小辉（基础运维专家）和小锋（应用运维专家），
**我想要** 在WeCube中对已经存在的任务编排进行删除，
**从而** 废除配置错误或者不适合再继续使用的任务编排。

### AC01. 删除
**假定** 小辉通过“协同 - 任务编排”菜单项进入任务编排页面，
**当** 他没有在“编排名称”列表中选择任何任务编排时，
**那么** 他应当在页面上看到“删除编排”动作按钮被禁用，

**当** 他在“编排名称”列表中选择了一个已有的任务编排时，
**那么** 他应当在页面上看到“删除编排”动作按钮被启用，
**当** 他点击“删除编排”按钮时，
**那么** WeCube应当弹出删除确认对话框，
**当** 他确认删除后，
**那么** 他应当在“编排名称”列表中找不到之前选择删除的任务编排，
并且删除后不影响任何已经执行过的任务编排记录的展示。

### 2019-12-05 PBR
1. 编排的删除和导出需要检查编排属主权限

## ETA: 
0 MD
## Owner:  
@HoweChen

**Comment by HoweChen** [comment]
@homiexie 
- [ ] 删除编排
DELETE: platform/v1/process
body: 
```
[
    "process_1",
    "process_2",
    "process_3"
]
```

response:
TBD

**Comment by kanetz** [comment]
> @homiexie
> 
> * [ ]  删除编排
>   DELETE: platform/v1/process
>   body:
> 
> ```
> [
>     "process_ID1",
>     "process_ID2",
>     "process_ID3"
> ]
> ```
> 
> response:
> TBD

👍推荐把最好商量好的api设计方案更新到1楼
