### ISSUE TITLE
系统参数 bugs

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#947]
**描述您遇到的bug**  
1. 范围没有值
1. 状态不更新
1. 分页不工作
1. 去掉显示顺序这一列
![image](https://user-images.githubusercontent.com/17263271/70372303-3fe36c80-1918-11ea-8208-5ebfe43f07b2.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by zhangsenfeng** [comment]
@jordanzhangsz ，以下3个问题经定位需要后台协助
1、“范围”列没有数据；
2、“状态”列的值始终为active；
3、查询接口中，分页信息里总页数不正确，总页数始终显示当前每页展示的数据行数。
