### ISSUE TITLE
编排任务执行时事件网关任务状态问题

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-platform#960]
**描述您遇到的bug**  
编排任务执行时事件网关任务状态问题：上一任务节点还在执行状态，事件网关任务已经成功。

![image](https://user-images.githubusercontent.com/17095701/70425758-badd8c00-1aac-11ea-811b-738c0c3c51ef.png)

**如何重现** 

**预期行为** 

**截图**  

**附加**

**Comment by gavin2lee** [comment]
fixed
