### ISSUE TITLE
日常运维操作的批量执行

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#985]
**作为** 小辉（基础运维专家）和小锋（应用运维专家）
**我想要** 检索指定范围内的CI数据对象
并且 针对这一批CI数据对象执行简单的运维操作（如执行脚本或调用其它插件服务等）
**从而** 能够灵活地完成一些随机性较强的日常运维管理工作

批量执行目前包括以下关联Issue：
- 操作对象查询：#987
- 执行操作并查看结果：#995
- 操作结果的过滤和搜索： #996

**Comment by chaneyliu** [comment]
v2.4.0版本的执行-批量执行 菜单内功能已支持。
