### ISSUE TITLE
[批量执行] 目标操作对象的查询

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#987]
## 关联的Issue
EPIC: #985 

## 背景和价值
**作为** 小辉和小锋，
**我想要** 检索一个指定范围的CI数据对象集合，
**从而** 灵活地确定运维操作执行的目标范围。

### AC01.  菜单项及批量执行页面
**假定** 小辉成功登录并访问WeCube，
**当** 他打开 “执行” 菜单时，
**那么** 他应当看到 “批量执行” 菜单项。

**当** 他通过菜单项访问批量执行页面时，
**那么** 他应当看到当前的查询路径和查询条件都没有定义，
并且 他此时还不能查询数据，
并且 他看应当看到页面上的 **“定义查询...”** 命令链接。

![image](https://user-images.githubusercontent.com/1160645/70680077-03c25a00-1cd2-11ea-93da-2f90c6d52a6e.png)

### AC02. 定义查询方式
**假定** 小辉成功登录并访问WeCube，
并且 他打开批量执行页面，
**当** 他点击 **“定义查询...”** 时，
**那么** 他应当可以在弹出的对话框中配置：

配置项 | 说明
-- | --
查询路径 | 以目标查询对象的数据类型为**终点**到某个关联的数据类型为止的数据模型表达式
目标类型 | 查询路径中最后一段的数据类型，从查询路径中自动解析
业务主键 | 目标类型的业务主键用作查询结果的主要显示属性
查询条件 | 从查询路径中的所有类型和属性中选择出将作为查询条件的数据属性

![image](https://user-images.githubusercontent.com/1160645/70963666-2a163a00-20c4-11ea-9bd5-36960900faa7.png)

**当** 小辉在 **“查询路径”** 中输入了合法的表达式时，
**那么** 他应当在 **“目标类型”** 中看到表达式中最后一段数据类型，
并且 他应当可以在 **“业务主键”** 列表中选择目标类型中的一个数据属性作为主要显示属性，
并且 他应当在 **“数据属性”** 的 **“候选数据类型及属性”** 中看到表达式中的所有数据类型和属性，
并且 查询方式中的各配置项情况如下表所示：

查询路径的数据模型表达式 | 查询目标对象的数据类型 | 数据属性列表中显示的数据类型 
-- | -- | --
资源实例 | 资源实例 | [1] 资源实例
资源集合~(资源集合)资源实例 | 资源实例 | [1] 资源集合、[2] 资源实例
数据中心~(数据中心)网络区域~(网络区域)业务区域~(业务区域)资源集合~(资源集合)资源实例 | 资源实例 | [1] 数据中心、[2] 网路区域、[3] 业务区域、[4] 资源集合、[5] 资源实例
系统~(系统)子系统~(子系统)部署单元~(部署单元)业务应用实例.资源实例>资源实例 | 资源实例 | [1] 系统、[2] 子系统、[3] 部署单元、[4] 业务应用实例、[5] 资源实例

**当** 小辉选择数据属性列表中的属性作为查询条件后，
**那么** 他可以点击“确认”完成对查询方式的配置，
并且 他可以在页面上看到配置并简化后的查询路径和查询条件，如下表所示：

输入的数据模型表达式 | 选择作为查询条件的数据属性 | 配置后的查询路径 | 配置后的查询条件
-- | -- | -- | --
资源实例 | [1] 资源实例.编码 | 资源实例 | [1] 资源实例.编码
资源集合~(资源集合)资源实例 | [1] 资源集合.编码 | 资源集合~(资源集合)资源实例 | [1] 资源集合.编码
数据中心~(数据中心)网络区域~(网络区域)业务区域~(业务区域)资源集合~(资源集合)资源实例 | [1] 数据中心.编码、[4]资源集合.编码 | 数据中心~(数据中心)网络区域~(网络区域)业务区域~(业务区域)资源集合~(资源集合)资源实例 | [1] 数据中心.编码、[4] 资源集合.编码
数据中心~(数据中心)网络区域~(网络区域)业务区域~(业务区域)资源集合~(资源集合)资源实例 | [4]资源集合.编码 | **资源集合~(资源集合)资源实例** | **[1] 资源集合.编码**

![image](https://user-images.githubusercontent.com/1160645/70691191-6e37c200-1cf3-11ea-8528-214cae05d6f2.png)

**2019-12-16 设计讨论结果：** 
- 为简化设计和操作，可考虑在输入完查询路径回车或输入框失去焦点后更新数据属性列表。
- 数据属性列表与已选择的查询条件整体可考虑采用穿梭框的方式进行实现。
- 当使用数据模型表达式配置查询路径时，假定用户以目标数据类型作为最终节点。

### AC03. 查询操作对象
**假定** 小辉成功登录并访问WeCube，
并且 在 **“批量执行”** 页面上完成了操作对象查询方式的配置（参照 **AC02**），
**当** 他输入查询条件值并点击 **“执行查询”** 时，
**那么** 他应当在页面上看到查询对象的数据类型以及查询条件值的概要信息，
并且 他应当在页面上看到查询结果列表。

![image](https://user-images.githubusercontent.com/1160645/70692193-c5d72d00-1cf5-11ea-88c6-83a9721f8ff6.png)

### AC04. 重新执行和定义查询
**假定** 小辉在 **“批量执行页面”** 上完成了操作对象的查询，
**当** 小辉点击页面上的 查询概要信息 的命令链接时，
**那么** 他应当看到WeCube弹出提示 **“将要清除结果列表并重新查询，是否继续？”**
**当** 小辉选择继续时，
**那么** 他应当看不到查询结果列表，
并且 他应当看到查询路径和查询条件的详细信息，
并且 他可以重新在页面上输入查询条件值，
**当** 他点击页面上的 **“定义查询...”** 命令链接时，
**那么** 他应当可以重新定义查询方式（参见 AC02）。

![image](https://user-images.githubusercontent.com/1160645/70767893-ec50a300-1d9d-11ea-8c77-508ab904f6ee.png)

![image](https://user-images.githubusercontent.com/1160645/70703112-60da0200-1d0a-11ea-9f71-0dbd27b92b67.png)

## 设计假定
- 当使用数据模型表达式配置查询路径时，假定用户以目标数据类型作为最终节点。

## API
- 执行查询

### 2019-12-26
定义好查询路径和条件后，用户在执行查询时仍可以选择不提供查询条件的输入值。此时，查询执行仍然按照预先定义好的查询路径执行，但实际上，执行的结果其实与仅保留最终节点的单级查询路径的结果等效。目前WeCube的系统行为没有在执行查询时对这种理论上可以简化的查询进行优化，目前的系统行为不影响用户使用场景，因此不作为此Issue的范围。

**Comment by kanetz** [comment]
**2019-12-16 前端设计讨论结果：** 
- 为简化设计和操作，可考虑在输入完查询路径回车或输入框失去焦点后更新数据属性列表。
- 数据属性列表与已选择的查询条件整体可考虑采用穿梭框的方式进行实现

**Comment by HoweChen** [comment]
任务拆分，现将 DME 的 json response 过滤功能作为#1111 来实现

**Comment by HoweChen** [comment]
#1111 DME with filter json format

https://github.com/WeBankPartners/wecube-platform/issues/1111#issuecomment-568631171

**Comment by HoweChen** [comment]
@pobu168 
增加 #1163 为前端提供支持

**Comment by kanetz** [comment]
定义好查询路径和条件后，用户在执行查询时仍可以选择不提供查询条件的输入值。此时，查询执行仍然按照预先定义好的查询路径执行，但实际上，执行的结果其实与仅保留最终节点的单级查询路径的结果等效。目前WeCube的系统行为没有在执行查询时对这种理论上可以简化的查询进行优化，目前的系统行为不影响用户使用场景，因此不作为此Issue的范围。
