### ISSUE TITLE
[批量执行] 操作结果的过滤与搜索

### ISSUE THREAD

**Issue by kanetz** [WeBankPartners/wecube-platform#996]
## 关联Issue
EPIC: #985 

## 背景和价值
**作为** 小辉和小锋，
**我想要** 在批量执行的操作结果中进行过滤和搜索，
**从而** 能快速地定位到想要查看的操作对象以及执行结果的成功、失败或错误信息，
以便获取关于此次操作执行的详细信息和协助问题的排查。

### AC01. 根据关键字过滤操作目标对象
**假定** 小辉在 **“批量执行”**页面 完成了一次运维操作的执行，
并且 在页面上看到操作的执行结果，
**当** 他在过滤操作对象输入框中输入关键字“keywords”并点击旁边的搜索按钮时，
**那么** 他应当看到下方的操作对象列表中只出现名称中匹配关键字“keywords”的操作对象，
**当** 他清除了输入框中的关键字时，
**那么** 他应当又能在操作对象列表中看到所有的操作对象。

![image](https://user-images.githubusercontent.com/1160645/70773462-802c6a00-1db2-11ea-96a2-7e4dbd126db5.png)

#### 关于关键字匹配的说明
推荐采用支持正则表达式的匹配方式

### AC02. 根据执行状态过滤操作目标对象
**假定** 小辉在 **“批量执行”**页面 完成了一次运维操作的执行，
并且 在页面上看到操作的执行结果，
**当** 他点击过滤操作对象输入框和搜索按钮右方的 **“状态过滤”** 按钮时，
**那么** 操作对象列表和状态过滤按钮应当如下表产生相应的变化：

当前的状态过滤按钮 | 点击后的状态过滤按钮 | 点击后的操作对象列表
-- | -- | --
显示灰色色块 | 显示红色色块 | 只显示执行结果为失败/错误的操作对象
显示红色色块 | 显示绿色色块 | 只显示执行结果为成功的操作对象
显示绿色色块 | 显示灰色色块 | 显示所有操作对象

### AC03. 在执行结果中搜索 - 匹配内容的数量
**假定** 小辉在 **“批量执行”**页面 完成了一次运维操作的执行，
并且 在页面上看到操作的执行结果，
**当** 他在操作结果搜索输入框中输入关键字“keyword”并点击右侧按钮时，
**那么** 他应当在左侧的操作对象列表中看到每个操作对象名称右侧显示该对象操作结果中与关键字“keyword”匹配到的内容位置的数量（如果某个操作对象的结果中没有匹配的内容，他应当在该操作对象名称右侧看不到任何内容，
**当** 他清除操作结果搜索输入框中的内容时，
**那么** 他应当在左侧的操作对象列表中找不到任何匹配数量的信息。

![image](https://user-images.githubusercontent.com/1160645/70774424-3b560280-1db5-11ea-824a-d1f4d923ddd5.png)

### AC04. 在执行结果中搜索 - 匹配内容的位置
**假定** 小辉在 **“批量执行”**页面 完成了一次运维操作的执行，
并且 在页面上看到操作的执行结果，
**当** 他在操作结果搜索输入框中输入关键字“keyword”并点击导航按钮，
**那么** 他应当发现结果窗口的定位位置发生如下变化：

匹配状态 | 当前显示的匹配位置 | 导航按钮状态 | 点击的导航按钮 | 应当显示的新匹配位置
-- | -- | -- | -- | --
有匹配内容 | 不是最后一个匹配位置 | 均被启用 | 下一个 | 下一个匹配位置
有匹配内容 | 最后一个匹配位置 | 均被启用 | 下一个 | 第一个匹配位置
有匹配内容 | 不是第一个匹配位置 | 均被启用 | 上一个 | 上一个匹配位置
有匹配内容 | 第一个匹配位置 | 均被启用 | 上一个 | 最后一个匹配位置
没有匹配内容 | | 均被禁用 | |

**Comment by kanetz** [comment]
从2.1版本范围中移出

**Comment by chaneyliu** [comment]
V2.4.0版本已支持此功能。
